#!/usr/bin/env python3
"""
Palette Position Rule Hunt — Comprehensive Investigation

TASK: Determine the rule that selects WHICH 17 of the 35 palette-character
positions in K4 are consensus nulls.

KNOWN:
- Palette {B,G,I,K,O,W,Z} generated by KRYPTOS + SEVEN on KA 5-wide Polybius grid
- 17 consensus nulls: {0,1,2,5,8,12,14,20,36,52,58,59,74,75,78,84,85}
- 18 non-null palette: {7,16,18,19,30,31,34,45,46,47,48,56,62,70,73,77,86,93}
- 4 crib positions forced non-null: {30,31,70,73}
- KA Beaufort key=N maps SEVEN -> palette
- N = 13 in AZ, 19 in KA
- SEVEN = S(18),E(4),V(21),E(4),N(13) in AZ

APPROACH: Exhaustive search over ~10 families of simple rules.
"""
# DEPRECATED: This script is retained as a historical artifact.
# Superseded by newer analysis. Do not cite results as current.
# See docs/SCRIPT_RIGOR_STANDARD.md

import sys
import os
import json
from collections import Counter, defaultdict
from itertools import combinations, product
from datetime import datetime, timezone
from math import comb

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'src'))
from kryptos.kernel.constants import CT, CT_LEN, KRYPTOS_ALPHABET, ALPH

# ── Constants ─────────────────────────────────────────────────────────────
PALETTE = frozenset('BGIKOWZ')
CONSENSUS_NULLS = frozenset({0,1,2,5,8,12,14,20,36,52,58,59,74,75,78,84,85})
ENE_POS = set(range(21, 34))
BCL_POS = set(range(63, 74))
CRIB_POS = ENE_POS | BCL_POS

KA = KRYPTOS_ALPHABET  # KRYPTOSABCDEFGHIJLMNQUVWXZ
KA_IDX = {c: i for i, c in enumerate(KA)}
AZ_IDX = {c: i for i, c in enumerate(ALPH)}

# All 35 palette positions in K4
palette_positions = sorted(p for p in range(CT_LEN) if CT[p] in PALETTE)
null_palette = sorted(p for p in palette_positions if p in CONSENSUS_NULLS)
nonnull_palette = sorted(p for p in palette_positions if p not in CONSENSUS_NULLS)

assert len(palette_positions) == 35
assert len(null_palette) == 17
assert len(nonnull_palette) == 18

# SEVEN and KRYPTOS as numeric values
SEVEN_AZ = [AZ_IDX[c] for c in 'SEVEN']   # [18, 4, 21, 4, 13]
SEVEN_KA = [KA_IDX[c] for c in 'SEVEN']   # S=6, E=11, V=22, E=11, N=19
KRYPTOS_AZ = [AZ_IDX[c] for c in 'KRYPTOS']  # [10,17,24,15,19,14,18]
KRYPTOS_KA = [KA_IDX[c] for c in 'KRYPTOS']  # [0,1,2,3,4,5,6]
DEFECTOR_AZ = [AZ_IDX[c] for c in 'DEFECTOR']  # [3,4,5,4,2,19,14,17]

# 6 known 15/24 masks
MASKS_24 = [
    [0,1,2,5,8,12,14,20,36,38,39,40,52,55,58,59,74,75,78,84,85,88,94,96],
    [0,1,2,5,8,12,14,20,36,39,41,43,52,56,58,59,74,75,78,84,85,88,93,95],
    [0,1,2,5,8,12,14,20,36,42,43,44,52,55,58,59,74,75,78,84,85,88,94,95],
    [0,1,2,5,8,12,14,20,36,39,41,42,52,55,58,59,74,75,78,84,85,88,93,95],
    [0,1,2,5,8,12,14,20,36,38,39,45,52,56,58,59,74,75,78,84,85,87,93,95],
    [0,1,2,5,8,12,14,20,36,41,42,44,52,55,58,59,74,75,78,84,85,88,93,96],
]

def k4_to_grid(pos):
    """Map K4 linear position to 28x31 grid (row, col)."""
    if pos < 4: return (24, 27 + pos)
    elif pos < 35: return (25, pos - 4)
    elif pos < 66: return (26, pos - 35)
    else: return (27, pos - 66)

# Labels: True = null, False = non-null
labels = {p: p in CONSENSUS_NULLS for p in palette_positions}

def score_rule(predicted_nulls_set):
    """Score a rule: returns (correct, tp, fp, fn, tn)."""
    tp = sum(1 for p in palette_positions if p in predicted_nulls_set and labels[p])
    fp = sum(1 for p in palette_positions if p in predicted_nulls_set and not labels[p])
    fn = sum(1 for p in palette_positions if p not in predicted_nulls_set and labels[p])
    tn = sum(1 for p in palette_positions if p not in predicted_nulls_set and not labels[p])
    return (tp + tn, tp, fp, fn, tn)

results = {'timestamp': datetime.now(timezone.utc).isoformat(), 'phases': {}}
all_rules = []  # (accuracy, description, predicted_null_set)

print("=" * 90)
print("PALETTE POSITION RULE HUNT — COMPREHENSIVE INVESTIGATION")
print("=" * 90)
print(f"CT = {CT}")
print(f"Palette = {sorted(PALETTE)}")
print(f"35 palette positions: {palette_positions}")
print(f"17 null: {null_palette}")
print(f"18 non-null: {nonnull_palette}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 1: SEVEN-derived position rules
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 1: SEVEN-DERIVED POSITION RULES")
print("=" * 90)

# 1a. position mod 5 (len(SEVEN)) -> null/non-null
print("\n--- 1a: pos mod 5 as predictor ---")
for r in range(5):
    n_null = sum(1 for p in null_palette if p % 5 == r)
    n_nonnull = sum(1 for p in nonnull_palette if p % 5 == r)
    print(f"  pos%5={r}: null={n_null}, nonnull={n_nonnull}")

# 1b. SEVEN[pos % 5] interacts with CT to determine null
print("\n--- 1b: Beaufort(CT[p], SEVEN[p%5]) in some set ---")
for p in palette_positions:
    s_val = SEVEN_AZ[p % 5]
    ct_val = AZ_IDX[CT[p]]
    beau = (s_val - ct_val) % 26
    vig = (ct_val - s_val) % 26
    beau_sum = (s_val + ct_val) % 26
    label = "NULL" if labels[p] else "    "
    print(f"  pos={p:>2} CT={CT[p]}({ct_val:>2}) SEVEN[{p%5}]={ALPH[s_val]}({s_val:>2}) "
          f"beau(CT+S)={ALPH[beau_sum]}({beau_sum:>2}) vig(CT-S)={ALPH[vig]}({vig:>2}) "
          f"beau(S-CT)={ALPH[beau]}({beau:>2}) {label}")

# Check: is null determined by (CT+SEVEN[pos%5]) mod 26 falling in some set?
null_beau_sums = set()
nonnull_beau_sums = set()
for p in palette_positions:
    val = (AZ_IDX[CT[p]] + SEVEN_AZ[p % 5]) % 26
    if labels[p]:
        null_beau_sums.add(val)
    else:
        nonnull_beau_sums.add(val)

overlap = null_beau_sums & nonnull_beau_sums
print(f"\n  (CT+SEVEN[pos%5])%26 for nulls: {sorted(null_beau_sums)}")
print(f"  (CT+SEVEN[pos%5])%26 for nonnulls: {sorted(nonnull_beau_sums)}")
print(f"  Overlap (prevents clean separation): {sorted(overlap)}")

# 1c. Same with KA indices
print("\n--- 1c: KA-Beaufort interactions ---")
null_ka_beau = set()
nonnull_ka_beau = set()
for p in palette_positions:
    s_val = SEVEN_KA[p % 5]
    ct_val = KA_IDX[CT[p]]
    beau = (s_val - ct_val) % 26
    if labels[p]:
        null_ka_beau.add(beau)
    else:
        nonnull_ka_beau.add(beau)
print(f"  KA_Beau(SEVEN[pos%5], CT[p]) for nulls: {sorted(null_ka_beau)}")
print(f"  KA_Beau(SEVEN[pos%5], CT[p]) for nonnulls: {sorted(nonnull_ka_beau)}")
print(f"  Overlap: {sorted(null_ka_beau & nonnull_ka_beau)}")

# 1d. Test all possible (a*pos + b*ct_val) mod M thresholds with SEVEN
for variant_name, fn in [
    ("(CT_AZ + SEVEN_AZ[p%5]) % 26", lambda p: (AZ_IDX[CT[p]] + SEVEN_AZ[p % 5]) % 26),
    ("(CT_AZ - SEVEN_AZ[p%5]) % 26", lambda p: (AZ_IDX[CT[p]] - SEVEN_AZ[p % 5]) % 26),
    ("(SEVEN_AZ[p%5] - CT_AZ) % 26", lambda p: (SEVEN_AZ[p % 5] - AZ_IDX[CT[p]]) % 26),
    ("(CT_KA + SEVEN_KA[p%5]) % 26", lambda p: (KA_IDX[CT[p]] + SEVEN_KA[p % 5]) % 26),
    ("(CT_KA - SEVEN_KA[p%5]) % 26", lambda p: (KA_IDX[CT[p]] - SEVEN_KA[p % 5]) % 26),
    ("(SEVEN_KA[p%5] - CT_KA) % 26", lambda p: (SEVEN_KA[p % 5] - KA_IDX[CT[p]]) % 26),
]:
    null_vals = [fn(p) for p in null_palette]
    nonnull_vals = [fn(p) for p in nonnull_palette]
    null_set = set(null_vals)
    nonnull_set = set(nonnull_vals)
    overlap_count = len(null_set & nonnull_set)
    # Try mod M reduction
    for M in [2,3,5,7,13]:
        null_mod = set(v % M for v in null_vals)
        nonnull_mod = set(v % M for v in nonnull_vals)
        if not (null_mod & nonnull_mod):
            print(f"  PERFECT MOD-{M} SEPARATION: {variant_name} mod {M}")
            print(f"    null residues: {sorted(null_mod)}, nonnull residues: {sorted(nonnull_mod)}")
    # Best single threshold
    for thresh in range(26):
        pred_null = set(p for p in palette_positions if fn(p) < thresh)
        acc, tp, fp, fneg, tn = score_rule(pred_null)
        if acc >= 32:
            desc = f"{variant_name} < {thresh}"
            all_rules.append((acc, desc, pred_null))

# ══════════════════════════════════════════════════════════════════════════
# PHASE 2: Key-N derived rules
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 2: KEY-N DERIVED RULES (N=13 in AZ, N=19 in KA)")
print("=" * 90)

for N_val, N_name in [(13, "N_AZ=13"), (19, "N_KA=19")]:
    for idx_name, idx_fn in [("AZ", lambda c: AZ_IDX[c]), ("KA", lambda c: KA_IDX[c])]:
        print(f"\n--- {N_name} with {idx_name} indices ---")
        # null if (CT_val + N) mod 26 satisfies condition?
        for op_name, op_fn in [
            (f"(CT_{idx_name} + {N_val}) % 26", lambda p, N=N_val, idx=idx_fn: (idx(CT[p]) + N) % 26),
            (f"(CT_{idx_name} - {N_val}) % 26", lambda p, N=N_val, idx=idx_fn: (idx(CT[p]) - N) % 26),
            (f"({N_val} - CT_{idx_name}) % 26", lambda p, N=N_val, idx=idx_fn: (N - idx(CT[p])) % 26),
        ]:
            null_vals = sorted(set(op_fn(p) for p in null_palette))
            nonnull_vals = sorted(set(op_fn(p) for p in nonnull_palette))
            overlap = set(null_vals) & set(nonnull_vals)
            if not overlap:
                print(f"  *** PERFECT: {op_name} separates! null={null_vals}, nonnull={nonnull_vals}")
            for M in [2,3,5,7,13]:
                null_mod = set(op_fn(p) % M for p in null_palette)
                nonnull_mod = set(op_fn(p) % M for p in nonnull_palette)
                if not (null_mod & nonnull_mod):
                    print(f"  PERFECT MOD-{M}: {op_name} mod {M}, null={sorted(null_mod)}, nonnull={sorted(nonnull_mod)}")

    # position + N
    for M in [26, 31, 97, 7, 13, 5]:
        null_mod = set((p + N_val) % M for p in null_palette)
        nonnull_mod = set((p + N_val) % M for p in nonnull_palette)
        if not (null_mod & nonnull_mod):
            print(f"  PERFECT: (pos + {N_val}) % {M}, null={sorted(null_mod)}, nonnull={sorted(nonnull_mod)}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 3: Beaufort keystream at null positions -> palette membership
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 3: AUTOKEY KEYSTREAM AT PALETTE POSITIONS")
print("=" * 90)

# Under DEFECTOR:AZ_beau autokey: key[p] = DEFECTOR[p] for p<8, key[p] = PT[p-8] for p>=8
# Beaufort: PT = (key - CT) mod 26 => key = (PT + CT) mod 26
# We know PT at crib positions. We can compute key at crib positions.
# key[21..33] = PT[13..25] (unknown). key[63..73] = PT[55..65] (unknown).
# But we know: key[p] for p < 8 = DEFECTOR[p].

# Compute what we can of the autokey chain
print("\nDEFECTOR:AZ_beau autokey first 8 positions:")
for p in range(8):
    key_val = DEFECTOR_AZ[p]
    ct_val = AZ_IDX[CT[p]]
    pt_val = (key_val - ct_val) % 26
    pt_char = ALPH[pt_val]
    is_palette = CT[p] in PALETTE
    is_null = p in CONSENSUS_NULLS
    print(f"  p={p} CT={CT[p]}({ct_val}) key=DEFECTOR[{p}]={ALPH[key_val]}({key_val}) "
          f"PT={pt_char}({pt_val}) palette={is_palette} null={is_null}")
    # Is key_val in palette AZ values?
    palette_az_vals = set(AZ_IDX[c] for c in PALETTE)
    print(f"    key ∈ palette? {key_val in palette_az_vals} (palette AZ = {sorted(palette_az_vals)})")

# Check: for first 8 positions, is "null iff DEFECTOR key ∈ palette"?
palette_az_vals = set(AZ_IDX[c] for c in PALETTE)
print("\nFirst 8 positions: null iff key ∈ palette?")
for p in range(8):
    key_val = DEFECTOR_AZ[p]
    predicted_null = key_val in palette_az_vals
    actual_null = p in CONSENSUS_NULLS
    match = "MATCH" if predicted_null == actual_null else "MISMATCH"
    print(f"  p={p}: key={ALPH[key_val]}({key_val}), key∈palette={predicted_null}, actual_null={actual_null} {match}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 4: KRYPTOS-derived column rules
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 4: KRYPTOS[pos%7] INTERACTION")
print("=" * 90)

# KRYPTOS letter at pos%7
print("\nKRYPTOS[pos%7] for each palette position:")
for p in palette_positions:
    kw_letter = 'KRYPTOS'[p % 7]
    kw_az = AZ_IDX[kw_letter]
    kw_ka = KA_IDX[kw_letter]
    ct_az = AZ_IDX[CT[p]]
    ct_ka = KA_IDX[CT[p]]
    label = "NULL" if labels[p] else "    "
    print(f"  p={p:>2} CT={CT[p]}({ct_az:>2}/{ct_ka:>2}) KW={kw_letter}({kw_az:>2}/{kw_ka:>2}) "
          f"CT_AZ+KW_AZ={((ct_az+kw_az)%26):>2} CT_KA+KW_KA={((ct_ka+kw_ka)%26):>2} {label}")

# null iff KRYPTOS[pos%7] is in some set?
null_kw = Counter('KRYPTOS'[p % 7] for p in null_palette)
nonnull_kw = Counter('KRYPTOS'[p % 7] for p in nonnull_palette)
print(f"\nKRYPTOS[pos%7] frequency for nulls: {dict(null_kw)}")
print(f"KRYPTOS[pos%7] frequency for non-nulls: {dict(nonnull_kw)}")
# No clean separation by KRYPTOS letter alone

# Try: (KRYPTOS_KA[p%7] + CT_KA) mod M for various M
for op_name, op_fn in [
    ("(KW_AZ + CT_AZ) % 26", lambda p: (AZ_IDX['KRYPTOS'[p%7]] + AZ_IDX[CT[p]]) % 26),
    ("(KW_AZ - CT_AZ) % 26", lambda p: (AZ_IDX['KRYPTOS'[p%7]] - AZ_IDX[CT[p]]) % 26),
    ("(CT_AZ - KW_AZ) % 26", lambda p: (AZ_IDX[CT[p]] - AZ_IDX['KRYPTOS'[p%7]]) % 26),
    ("(KW_KA + CT_KA) % 26", lambda p: (KA_IDX['KRYPTOS'[p%7]] + KA_IDX[CT[p]]) % 26),
    ("(KW_KA - CT_KA) % 26", lambda p: (KA_IDX['KRYPTOS'[p%7]] - KA_IDX[CT[p]]) % 26),
    ("(CT_KA - KW_KA) % 26", lambda p: (KA_IDX[CT[p]] - KA_IDX['KRYPTOS'[p%7]]) % 26),
]:
    null_vals = set(op_fn(p) for p in null_palette)
    nonnull_vals = set(op_fn(p) for p in nonnull_palette)
    if not (null_vals & nonnull_vals):
        print(f"  *** PERFECT: {op_name} separates! null={sorted(null_vals)}, nonnull={sorted(nonnull_vals)}")
    for M in [2,3,5,7,13]:
        null_mod = set(op_fn(p) % M for p in null_palette)
        nonnull_mod = set(op_fn(p) % M for p in nonnull_palette)
        if not (null_mod & nonnull_mod):
            print(f"  PERFECT MOD-{M}: {op_name} mod {M}, null={sorted(null_mod)}, nonnull={sorted(nonnull_mod)}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 5: Combined KRYPTOS + SEVEN positional rule
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 5: COMBINED KRYPTOS[pos%7] + SEVEN[pos%5] RULES")
print("=" * 90)

for op_name, op_fn in [
    ("KW_AZ[p%7]+SV_AZ[p%5]+CT_AZ",  lambda p: (AZ_IDX['KRYPTOS'[p%7]] + SEVEN_AZ[p%5] + AZ_IDX[CT[p]]) % 26),
    ("KW_AZ[p%7]+SV_AZ[p%5]-CT_AZ",  lambda p: (AZ_IDX['KRYPTOS'[p%7]] + SEVEN_AZ[p%5] - AZ_IDX[CT[p]]) % 26),
    ("KW_AZ[p%7]-SV_AZ[p%5]+CT_AZ",  lambda p: (AZ_IDX['KRYPTOS'[p%7]] - SEVEN_AZ[p%5] + AZ_IDX[CT[p]]) % 26),
    ("KW_AZ[p%7]-SV_AZ[p%5]-CT_AZ",  lambda p: (AZ_IDX['KRYPTOS'[p%7]] - SEVEN_AZ[p%5] - AZ_IDX[CT[p]]) % 26),
    ("KW_KA[p%7]+SV_KA[p%5]+CT_KA",  lambda p: (KA_IDX['KRYPTOS'[p%7]] + SEVEN_KA[p%5] + KA_IDX[CT[p]]) % 26),
    ("KW_KA[p%7]+SV_KA[p%5]-CT_KA",  lambda p: (KA_IDX['KRYPTOS'[p%7]] + SEVEN_KA[p%5] - KA_IDX[CT[p]]) % 26),
    ("KW_KA[p%7]-SV_KA[p%5]+CT_KA",  lambda p: (KA_IDX['KRYPTOS'[p%7]] - SEVEN_KA[p%5] + KA_IDX[CT[p]]) % 26),
    ("KW_KA[p%7]-SV_KA[p%5]-CT_KA",  lambda p: (KA_IDX['KRYPTOS'[p%7]] - SEVEN_KA[p%5] - KA_IDX[CT[p]]) % 26),
]:
    null_vals = set(op_fn(p) for p in null_palette)
    nonnull_vals = set(op_fn(p) for p in nonnull_palette)
    overlap = null_vals & nonnull_vals
    for M in [2,3,5,7,13]:
        null_mod = set(op_fn(p) % M for p in null_palette)
        nonnull_mod = set(op_fn(p) % M for p in nonnull_palette)
        if not (null_mod & nonnull_mod):
            print(f"  PERFECT MOD-{M}: {op_name} mod {M}, null={sorted(null_mod)}, nonnull={sorted(nonnull_mod)}")
    # Also try: is the value itself in the palette AZ set?
    null_in_pal = sum(1 for p in null_palette if op_fn(p) in palette_az_vals)
    nonnull_in_pal = sum(1 for p in nonnull_palette if op_fn(p) in palette_az_vals)
    if null_in_pal >= 15 and nonnull_in_pal <= 2:
        print(f"  STRONG: {op_name} ∈ palette: null={null_in_pal}/17, nonnull={nonnull_in_pal}/18")
    elif null_in_pal <= 2 and nonnull_in_pal >= 15:
        print(f"  STRONG (inverted): {op_name} ∈ palette: null={null_in_pal}/17, nonnull={nonnull_in_pal}/18")

# Also: null if (KW_KA[p%7] + SV_KA[p%5]) mod 26 is in palette?
# (This doesn't use CT at all — pure positional)
print("\n--- Positional only (no CT): KRYPTOS[p%7] + SEVEN[p%5] ---")
for op_name, op_fn in [
    ("(KW_AZ[p%7]+SV_AZ[p%5])%26", lambda p: (AZ_IDX['KRYPTOS'[p%7]] + SEVEN_AZ[p%5]) % 26),
    ("(KW_AZ[p%7]-SV_AZ[p%5])%26", lambda p: (AZ_IDX['KRYPTOS'[p%7]] - SEVEN_AZ[p%5]) % 26),
    ("(KW_KA[p%7]+SV_KA[p%5])%26", lambda p: (KA_IDX['KRYPTOS'[p%7]] + SEVEN_KA[p%5]) % 26),
    ("(KW_KA[p%7]-SV_KA[p%5])%26", lambda p: (KA_IDX['KRYPTOS'[p%7]] - SEVEN_KA[p%5]) % 26),
]:
    print(f"\n  {op_name}:")
    for p in palette_positions:
        val = op_fn(p)
        letter = ALPH[val]
        label = "NULL" if labels[p] else "    "
        in_pal = "PAL" if val in palette_az_vals else "   "
        print(f"    p={p:>2} -> {val:>2} ({letter}) {in_pal} {label}")

    null_vals = set(op_fn(p) for p in null_palette)
    nonnull_vals = set(op_fn(p) for p in nonnull_palette)
    print(f"  Null values: {sorted(null_vals)}, Non-null values: {sorted(nonnull_vals)}")
    print(f"  Overlap: {sorted(null_vals & nonnull_vals)}")

    for M in [2,3,5,7,13,26]:
        null_mod = set(op_fn(p) % M for p in null_palette)
        nonnull_mod = set(op_fn(p) % M for p in nonnull_palette)
        if not (null_mod & nonnull_mod):
            print(f"  *** PERFECT MOD-{M}: null={sorted(null_mod)}, nonnull={sorted(nonnull_mod)}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 6: Grid-position + keyword rule
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 6: GRID POSITION + KEYWORD INTERACTION")
print("=" * 90)

# K4 grid: rows 24-27, cols 0-30 (except first 4 at row 24 cols 27-30)
# KRYPTOS[col % 7] and SEVEN[(row-24) % 5]
print("\n--- KRYPTOS[col%7] and SEVEN[(row-24)%5] ---")
for p in palette_positions:
    row, col = k4_to_grid(p)
    kw_letter = 'KRYPTOS'[col % 7]
    row_offset = row - 24
    sv_letter = 'SEVEN'[row_offset % 5]
    label = "NULL" if labels[p] else "    "
    print(f"  p={p:>2} row={row} col={col:>2} KW[col%7]={kw_letter} SV[row%5]={sv_letter} {label}")

# Check: null iff (kw_letter, sv_letter) is in some specific set?
null_pairs = Counter()
nonnull_pairs = Counter()
for p in palette_positions:
    row, col = k4_to_grid(p)
    kw_letter = 'KRYPTOS'[col % 7]
    sv_letter = 'SEVEN'[(row-24) % 5]
    pair = (kw_letter, sv_letter)
    if labels[p]:
        null_pairs[pair] += 1
    else:
        nonnull_pairs[pair] += 1

print(f"\n  (KW[col%7], SV[row%5]) pairs:")
all_kw_letters = sorted(set('KRYPTOS'))
all_sv_letters = sorted(set('SEVEN'))
for kw in all_kw_letters:
    for sv in all_sv_letters:
        n = null_pairs.get((kw,sv), 0)
        nn = nonnull_pairs.get((kw,sv), 0)
        if n + nn > 0:
            purity = "ALL-NULL" if nn == 0 else "ALL-NONNULL" if n == 0 else "MIXED"
            print(f"    ({kw},{sv}): null={n}, nonnull={nn} {purity}")

# Try 7x5 grid as a mask
print("\n--- 7x5 positional mask (pos%7, pos%5) ---")
null_mask_7x5 = defaultdict(list)
nonnull_mask_7x5 = defaultdict(list)
for p in palette_positions:
    cell = (p % 7, p % 5)
    if labels[p]:
        null_mask_7x5[cell].append(p)
    else:
        nonnull_mask_7x5[cell].append(p)

print("  7x5 grid (palette positions):")
for c5 in range(5):
    for c7 in range(7):
        cell = (c7, c5)
        n = len(null_mask_7x5.get(cell, []))
        nn = len(nonnull_mask_7x5.get(cell, []))
        if n + nn == 0:
            print(f"  ({c7},{c5}): ---", end="  ")
        else:
            pure = "N" if nn == 0 else "R" if n == 0 else "M"
            print(f"  ({c7},{c5}): {n}N{nn}R {pure}", end="  ")
    print()

# Can we find a 7x5 cell mask that perfectly separates?
# Since period 7*5=35 and we have 35 palette positions... but they're not uniformly distributed
# Instead, check: for each (p%7, p%5) cell, is it pure?
pure_cells = 0
mixed_cells = 0
for cell in set(list(null_mask_7x5.keys()) + list(nonnull_mask_7x5.keys())):
    n = len(null_mask_7x5.get(cell, []))
    nn = len(nonnull_mask_7x5.get(cell, []))
    if n > 0 and nn > 0:
        mixed_cells += 1
    elif n > 0 or nn > 0:
        pure_cells += 1
print(f"\n  Pure cells: {pure_cells}, Mixed cells: {mixed_cells}")
if mixed_cells == 0:
    print(f"  *** PERFECT: (pos%7, pos%5) cell membership perfectly separates null/non-null! ***")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 7: DEFECTOR connection — key analysis for first 8 positions
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 7: DEFECTOR KEY + NULL STATUS AT FIRST 8 POSITIONS")
print("=" * 90)

# DEFECTOR = D(3),E(4),F(5),E(4),C(2),T(19),O(14),R(17)
# Null positions in first 8: {0,1,2,5}
# Non-null: {3,4,6,7}
# Key at null positions: D(3),E(4),F(5),T(19) — D,E,F are consecutive!
# Key at non-null: E(4),C(2),O(14),R(17)

# The null positions {0,1,2,5} have key values {3,4,5,19}
# The first three (D,E,F) are positions 0,1,2 with values 3,4,5 = three consecutive
# Position 5 has T=19

# Check: are null positions those where key_val mod 5 ∈ {3,4,0}?
# D=3%5=3, E=4%5=4, F=5%5=0, T=19%5=4  → {0,3,4}
# E=4%5=4, C=2%5=2, O=14%5=4, R=17%5=2 → {2,4}
# Overlap at 4 — NOT clean

# Check: key in palette?
print("\nDEFECTOR key values (AZ) at palette positions in first 8:")
palette_az_set = set(AZ_IDX[c] for c in PALETTE)
for p in range(8):
    if CT[p] in PALETTE:
        key_val = DEFECTOR_AZ[p]
        is_null = p in CONSENSUS_NULLS
        in_pal = key_val in palette_az_set
        print(f"  p={p}: key={ALPH[key_val]}({key_val}), key∈palette={in_pal}, null={is_null}")

# Key analysis: D=3, E=4, F=5 are the DEFECTOR letters where AZ_val < 6 (A-F)
# T=19 breaks this pattern. But T is at position 5 (the 6th letter of DEFECTOR).
# Check: null if key_val is in {D,E,F} (first 6 letters) OR if key_val = T?
# More general: null if key_val ∈ {3,4,5,19}? This is just listing the observed values.

# Check: is there a relationship between key_val and CT_val at null positions?
print("\nKey-CT relationships at first 8 palette positions:")
for p in range(8):
    if CT[p] in PALETTE:
        key_val = DEFECTOR_AZ[p]
        ct_val = AZ_IDX[CT[p]]
        is_null = p in CONSENSUS_NULLS
        print(f"  p={p}: key={key_val}, CT={ct_val}, key+CT={key_val+ct_val}, "
              f"key-CT={(key_val-ct_val)%26}, key*CT={key_val*ct_val}, null={is_null}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 8: Exhaustive search for simple rules
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 8: EXHAUSTIVE SIMPLE RULE SEARCH")
print("=" * 90)

# 8a. (a * pos + b) mod M ∈ S for various a, b, M, S
print("\n--- 8a: (a*pos + b) mod M rules (M ≤ 31) ---")
best_linear = []
for M in range(2, 32):
    for a in range(M):
        for b in range(M):
            null_residues = set((a * p + b) % M for p in null_palette)
            nonnull_residues = set((a * p + b) % M for p in nonnull_palette)
            if not (null_residues & nonnull_residues):
                # Perfect separation by value
                pred_null = set(p for p in palette_positions if (a*p+b) % M in null_residues)
                acc, tp, fp, fn, tn = score_rule(pred_null)
                if acc == 35:
                    best_linear.append((M, a, b, sorted(null_residues), sorted(nonnull_residues)))

if best_linear:
    print(f"  PERFECT linear rules found: {len(best_linear)}")
    for M, a, b, nr, nnr in best_linear[:20]:
        print(f"    ({a}*pos+{b}) mod {M}: null∈{nr}, nonnull∈{nnr}")
else:
    print(f"  No perfect linear position rules found.")
    # Find best approximations
    best_approx = []
    for M in range(2, 20):
        for a in range(M):
            for b in range(M):
                vals = {p: (a*p+b) % M for p in palette_positions}
                for S_size in range(1, M):
                    # Try S = set of first S_size unique null residues
                    # More efficient: for each subset of residues, check accuracy
                    pass  # Too combinatorial; use simpler check
                # Best single threshold
                for thresh in range(M):
                    pred_null = set(p for p in palette_positions if vals[p] < thresh)
                    acc = sum(1 for p in palette_positions if (p in pred_null) == labels[p])
                    if acc >= 33:
                        best_approx.append((acc, M, a, b, thresh))
    best_approx.sort(key=lambda x: -x[0])
    if best_approx:
        print(f"  Best approximate (a*pos+b)%M < thresh rules (>=33/35):")
        for acc, M, a, b, thresh in best_approx[:10]:
            print(f"    ({a}*pos+{b}) mod {M} < {thresh}: {acc}/35")

# 8b. (a * KA_IDX(CT) + b * pos) mod M
print("\n--- 8b: (a*KA(CT) + b*pos) mod M rules ---")
best_mixed = []
for M in range(2, 15):
    for a in range(M):
        for b in range(M):
            null_res = set((a * KA_IDX[CT[p]] + b * p) % M for p in null_palette)
            nonnull_res = set((a * KA_IDX[CT[p]] + b * p) % M for p in nonnull_palette)
            if not (null_res & nonnull_res):
                pred_null = set(p for p in palette_positions if (a*KA_IDX[CT[p]]+b*p) % M in null_res)
                acc, tp, fp, fn, tn = score_rule(pred_null)
                if acc == 35:
                    best_mixed.append((M, a, b, sorted(null_res), sorted(nonnull_res)))

if best_mixed:
    print(f"  PERFECT mixed rules found: {len(best_mixed)}")
    for M, a, b, nr, nnr in best_mixed[:20]:
        print(f"    ({a}*KA(CT)+{b}*pos) mod {M}: null∈{nr}, nonnull∈{nnr}")
else:
    print(f"  No perfect mixed rules found.")

# Same with AZ indexing
best_mixed_az = []
for M in range(2, 15):
    for a in range(M):
        for b in range(M):
            null_res = set((a * AZ_IDX[CT[p]] + b * p) % M for p in null_palette)
            nonnull_res = set((a * AZ_IDX[CT[p]] + b * p) % M for p in nonnull_palette)
            if not (null_res & nonnull_res):
                pred_null = set(p for p in palette_positions if (a*AZ_IDX[CT[p]]+b*p) % M in null_res)
                acc, tp, fp, fn, tn = score_rule(pred_null)
                if acc == 35:
                    best_mixed_az.append((M, a, b, sorted(null_res), sorted(nonnull_res)))

if best_mixed_az:
    print(f"  PERFECT (AZ) mixed rules found: {len(best_mixed_az)}")
    for M, a, b, nr, nnr in best_mixed_az[:20]:
        print(f"    ({a}*AZ(CT)+{b}*pos) mod {M}: null∈{nr}, nonnull∈{nnr}")
else:
    print(f"  No perfect AZ mixed rules found.")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 9: The 13/26 connection — position mod 13
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 9: MODULUS 13 AND 26 ANALYSIS")
print("=" * 90)

print("\n--- Position mod 13 ---")
for r in range(13):
    n = sum(1 for p in null_palette if p % 13 == r)
    nn = sum(1 for p in nonnull_palette if p % 13 == r)
    print(f"  pos%13={r:>2}: null={n}, nonnull={nn}")

# (CT_AZ + pos) mod 13
print("\n--- (CT_AZ + pos) mod 13 ---")
null_vals = set((AZ_IDX[CT[p]] + p) % 13 for p in null_palette)
nonnull_vals = set((AZ_IDX[CT[p]] + p) % 13 for p in nonnull_palette)
print(f"  Null residues: {sorted(null_vals)}")
print(f"  Non-null residues: {sorted(nonnull_vals)}")
print(f"  Overlap: {sorted(null_vals & nonnull_vals)}")

# (CT_KA + pos) mod 13
null_vals = set((KA_IDX[CT[p]] + p) % 13 for p in null_palette)
nonnull_vals = set((KA_IDX[CT[p]] + p) % 13 for p in nonnull_palette)
print(f"\n  (CT_KA + pos) % 13:")
print(f"  Null residues: {sorted(null_vals)}")
print(f"  Non-null residues: {sorted(nonnull_vals)}")
print(f"  Overlap: {sorted(null_vals & nonnull_vals)}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 10: Check rules against ALL 6 known masks
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 10: CROSS-VALIDATION AGAINST 6 KNOWN 15/24 MASKS")
print("=" * 90)

# The 7 varying positions differ across masks. Do they follow any of the above patterns?
varying_positions = set()
for mask in MASKS_24:
    varying_positions |= (set(mask) - CONSENSUS_NULLS)

print(f"All varying null positions across 6 masks: {sorted(varying_positions)}")
print(f"Count: {len(varying_positions)}")

# For each mask, show the 7 varying positions
for i, mask in enumerate(MASKS_24):
    varying = sorted(set(mask) - CONSENSUS_NULLS)
    print(f"  Mask {i}: varying = {varying}")
    for p in varying:
        row, col = k4_to_grid(p)
        ct_char = CT[p]
        in_pal = ct_char in PALETTE
        print(f"    p={p:>2} CT={ct_char} row={row} col={col:>2} palette={in_pal}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 11: SEVEN as Beaufort keyword — cycling key
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 11: SEVEN AS CYCLING BEAUFORT KEY")
print("=" * 90)

# Under Beaufort with key SEVEN cycling:
# PT[p] = (SEVEN_AZ[p%5] - CT_AZ[p]) mod 26
# null if PT[p] is in palette?
print("\nBeau(SEVEN[p%5], CT[p]) for palette positions:")
for p in palette_positions:
    key_val = SEVEN_AZ[p % 5]
    ct_val = AZ_IDX[CT[p]]
    pt_val = (key_val - ct_val) % 26
    pt_char = ALPH[pt_val]
    in_pal = pt_char in PALETTE
    label = "NULL" if labels[p] else "    "
    match = "MATCH" if in_pal == labels[p] else "MISS"
    print(f"  p={p:>2} CT={CT[p]} key=SEVEN[{p%5}]={ALPH[key_val]} PT={pt_char} PT∈pal={in_pal} {label} {match}")

null_match = sum(1 for p in null_palette if ALPH[(SEVEN_AZ[p%5] - AZ_IDX[CT[p]]) % 26] in PALETTE)
nonnull_match = sum(1 for p in nonnull_palette if ALPH[(SEVEN_AZ[p%5] - AZ_IDX[CT[p]]) % 26] in PALETTE)
print(f"\n  'null iff Beau(SEVEN,CT) ∈ palette': null_correct={null_match}/17, nonnull_correct={18-nonnull_match}/18")
print(f"  Total accuracy: {null_match + 18 - nonnull_match}/35")

# Same with KA Beaufort
print("\nKA_Beau(SEVEN_KA[p%5], CT_KA) for palette positions:")
for p in palette_positions:
    key_val = SEVEN_KA[p % 5]
    ct_val = KA_IDX[CT[p]]
    pt_val = (key_val - ct_val) % 26
    pt_char = KA[pt_val]
    in_pal = pt_char in PALETTE
    label = "NULL" if labels[p] else "    "
    match = "MATCH" if in_pal == labels[p] else "MISS"
    print(f"  p={p:>2} CT={CT[p]} key=SEVEN_KA[{p%5}]={KA[key_val]} PT_KA={pt_char} PT∈pal={in_pal} {label} {match}")

null_match_ka = sum(1 for p in null_palette if KA[(SEVEN_KA[p%5] - KA_IDX[CT[p]]) % 26] in PALETTE)
nonnull_match_ka = sum(1 for p in nonnull_palette if KA[(SEVEN_KA[p%5] - KA_IDX[CT[p]]) % 26] in PALETTE)
print(f"\n  'null iff KA_Beau(SEVEN,CT) ∈ palette': null_correct={null_match_ka}/17, nonnull_correct={18-nonnull_match_ka}/18")
print(f"  Total accuracy: {null_match_ka + 18 - nonnull_match_ka}/35")

# Also try Vigenere and Variant Beaufort
for cipher_name, cipher_fn in [
    ("Vig(CT-key)", lambda ct, k: (ct - k) % 26),
    ("VBeau(key+CT)", lambda ct, k: (k + ct) % 26),
]:
    for alpha_name, alpha_idx, alpha_str in [("AZ", AZ_IDX, ALPH), ("KA", KA_IDX, KA)]:
        seven_vals = [alpha_idx[c] for c in 'SEVEN']
        null_match = sum(1 for p in null_palette
                        if alpha_str[cipher_fn(alpha_idx[CT[p]], seven_vals[p%5])] in PALETTE)
        nonnull_match = sum(1 for p in nonnull_palette
                          if alpha_str[cipher_fn(alpha_idx[CT[p]], seven_vals[p%5])] in PALETTE)
        acc = null_match + 18 - nonnull_match
        if acc >= 28 or acc <= 7:  # Also check inverted
            print(f"  {cipher_name}_{alpha_name}(SEVEN,CT)∈palette: acc={acc}/35")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 12: KA Polybius coordinate interaction
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 12: KA POLYBIUS COORDINATE INTERACTION")
print("=" * 90)

# In the 5-wide KA Polybius grid:
# KA_row = KA_IDX // 5, KA_col = KA_IDX % 5
# Palette = col ∈ {0,3}
# Can the palette position's Polybius coordinates interact with SEVEN/pos?

print("\nKA Polybius coordinates for each palette position:")
for p in palette_positions:
    ka_idx = KA_IDX[CT[p]]
    ka_row = ka_idx // 5
    ka_col = ka_idx % 5
    sv = SEVEN_AZ[p % 5]
    kw = AZ_IDX['KRYPTOS'[p % 7]]
    label = "NULL" if labels[p] else "    "
    print(f"  p={p:>2} CT={CT[p]} KA=({ka_row},{ka_col}) pos%5={p%5} pos%7={p%7} "
          f"sv={sv} kw={kw} row+sv%6={((ka_row+sv)%6)} {label}")

# null iff KA_row + SEVEN_AZ[pos%5] satisfies condition?
for op_name, op_fn in [
    ("KA_row + SEVEN[p%5]", lambda p: (KA_IDX[CT[p]]//5 + SEVEN_AZ[p%5])),
    ("KA_row - SEVEN[p%5]", lambda p: (KA_IDX[CT[p]]//5 - SEVEN_AZ[p%5])),
    ("KA_row * SEVEN[p%5]", lambda p: (KA_IDX[CT[p]]//5 * SEVEN_AZ[p%5])),
    ("KA_row + pos%5", lambda p: (KA_IDX[CT[p]]//5 + p%5)),
    ("KA_row + pos%7", lambda p: (KA_IDX[CT[p]]//5 + p%7)),
    ("KA_row * pos%5 + KA_col", lambda p: (KA_IDX[CT[p]]//5 * (p%5) + KA_IDX[CT[p]]%5)),
]:
    for M in [2,3,5,6,7,13,26]:
        null_res = set(op_fn(p) % M for p in null_palette)
        nonnull_res = set(op_fn(p) % M for p in nonnull_palette)
        if not (null_res & nonnull_res):
            print(f"  PERFECT: ({op_name}) mod {M}: null={sorted(null_res)}, nonnull={sorted(nonnull_res)}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 13: Grid column with SEVEN interaction
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 13: GRID COLUMN + SEVEN INTERACTION")
print("=" * 90)

# Actual grid column (0-30) + SEVEN[something]
for op_name, op_fn in [
    ("gcol + SEVEN_AZ[row%5]", lambda p: k4_to_grid(p)[1] + SEVEN_AZ[(k4_to_grid(p)[0]-24) % 5]),
    ("gcol - SEVEN_AZ[row%5]", lambda p: k4_to_grid(p)[1] - SEVEN_AZ[(k4_to_grid(p)[0]-24) % 5]),
    ("gcol + SEVEN_AZ[p%5]", lambda p: k4_to_grid(p)[1] + SEVEN_AZ[p % 5]),
    ("gcol - SEVEN_AZ[p%5]", lambda p: k4_to_grid(p)[1] - SEVEN_AZ[p % 5]),
    ("gcol * SEVEN_AZ[p%5]", lambda p: k4_to_grid(p)[1] * SEVEN_AZ[p % 5]),
    ("gcol + KRYPTOS_AZ[p%7]", lambda p: k4_to_grid(p)[1] + AZ_IDX['KRYPTOS'[p%7]]),
    ("gcol - KRYPTOS_AZ[p%7]", lambda p: k4_to_grid(p)[1] - AZ_IDX['KRYPTOS'[p%7]]),
]:
    for M in [2,3,5,7,8,13,26,31]:
        null_res = set(op_fn(p) % M for p in null_palette)
        nonnull_res = set(op_fn(p) % M for p in nonnull_palette)
        if not (null_res & nonnull_res):
            print(f"  PERFECT: ({op_name}) mod {M}: null={sorted(null_res)}, nonnull={sorted(nonnull_res)}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 14: N-specific rules
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 14: N-SPECIFIC RULES (N=13, key that maps SEVEN->palette)")
print("=" * 90)

# N = 13 in AZ. Does (pos + CT_AZ) mod 13 separate?
for op_name, op_fn in [
    ("(pos + CT_AZ) % 13", lambda p: (p + AZ_IDX[CT[p]]) % 13),
    ("(pos - CT_AZ) % 13", lambda p: (p - AZ_IDX[CT[p]]) % 13),
    ("(pos * CT_AZ) % 13", lambda p: (p * AZ_IDX[CT[p]]) % 13),
    ("(pos + CT_KA) % 13", lambda p: (p + KA_IDX[CT[p]]) % 13),
    ("(pos - CT_KA) % 13", lambda p: (p - KA_IDX[CT[p]]) % 13),
    ("(pos * 13 + CT_AZ) % 26", lambda p: (p * 13 + AZ_IDX[CT[p]]) % 26),
    ("(pos + 13 + CT_AZ) % 26", lambda p: (p + 13 + AZ_IDX[CT[p]]) % 26),
    ("(pos XOR 13)", lambda p: p ^ 13),
]:
    for M in [2,3,5,7,13,26]:
        null_res = set(op_fn(p) % M for p in null_palette)
        nonnull_res = set(op_fn(p) % M for p in nonnull_palette)
        if not (null_res & nonnull_res):
            print(f"  PERFECT: ({op_name}) mod {M}: null={sorted(null_res)}, nonnull={sorted(nonnull_res)}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 15: Comprehensive single-value function search
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 15: COMPREHENSIVE FUNCTION SEARCH f(p,CT) -> {null,nonnull}")
print("=" * 90)

# Build feature vector for each palette position
features = {}
for p in palette_positions:
    row, col = k4_to_grid(p)
    ct_az = AZ_IDX[CT[p]]
    ct_ka = KA_IDX[CT[p]]
    ka_row = ct_ka // 5
    ka_col = ct_ka % 5
    sv_az = SEVEN_AZ[p % 5]
    sv_ka = SEVEN_KA[p % 5]
    kw_az = AZ_IDX['KRYPTOS'[p % 7]]
    kw_ka = KA_IDX['KRYPTOS'[p % 7]]

    features[p] = {
        'pos': p,
        'row': row,
        'col': col,
        'ct_az': ct_az,
        'ct_ka': ct_ka,
        'ka_row': ka_row,
        'ka_col': ka_col,
        'p_mod5': p % 5,
        'p_mod7': p % 7,
        'p_mod13': p % 13,
        'sv_az': sv_az,
        'sv_ka': sv_ka,
        'kw_az': kw_az,
        'kw_ka': kw_ka,
        'col_mod7': col % 7,
        'col_mod8': col % 8,
    }

# Now test ALL f(feature1 op feature2) mod M
feature_names = ['pos', 'ct_az', 'ct_ka', 'ka_row', 'ka_col', 'sv_az', 'sv_ka',
                 'kw_az', 'kw_ka', 'col', 'row', 'p_mod5', 'p_mod7']
operations = [
    ('+', lambda a,b: a+b),
    ('-', lambda a,b: a-b),
    ('*', lambda a,b: a*b),
    ('^', lambda a,b: a^b),
]

perfect_rules_phase15 = []
near_perfect_rules = []

for f1_name in feature_names:
    for f2_name in feature_names:
        if f1_name == f2_name:
            continue
        for op_sym, op_fn in operations:
            for M in [2,3,5,7,13,26]:
                null_res = set(op_fn(features[p][f1_name], features[p][f2_name]) % M
                             for p in null_palette)
                nonnull_res = set(op_fn(features[p][f1_name], features[p][f2_name]) % M
                                for p in nonnull_palette)
                if not (null_res & nonnull_res):
                    desc = f"({f1_name} {op_sym} {f2_name}) % {M}: null∈{sorted(null_res)}, nonnull∈{sorted(nonnull_res)}"
                    perfect_rules_phase15.append(desc)

                # Also check near-perfect (34/35)
                for S in range(M):
                    pred_null = set(p for p in palette_positions
                                  if op_fn(features[p][f1_name], features[p][f2_name]) % M == S)
                    acc, tp, fp, fn, tn = score_rule(pred_null)
                    # Check both: null if in S, and null if NOT in S
                    acc2 = (17-tp) + fp + fn + (18-tn)  # inverted
                    acc2 = 35 - acc  # simpler

                    if acc >= 34:
                        near_perfect_rules.append((acc, f"({f1_name} {op_sym} {f2_name}) % {M} == {S} -> null: {acc}/35"))
                    if 35 - acc >= 34:
                        near_perfect_rules.append((35-acc, f"({f1_name} {op_sym} {f2_name}) % {M} != {S} -> null: {35-acc}/35"))

if perfect_rules_phase15:
    print(f"\n  PERFECT RULES FOUND: {len(perfect_rules_phase15)}")
    for desc in perfect_rules_phase15[:50]:
        print(f"    {desc}")
else:
    print(f"\n  No perfect f1 op f2 mod M rules found.")

near_perfect_rules.sort(key=lambda x: -x[0])
seen = set()
print(f"\n  Near-perfect rules (>=34/35):")
for acc, desc in near_perfect_rules:
    if desc not in seen:
        seen.add(desc)
        print(f"    {desc}")
    if len(seen) >= 30:
        break

# ══════════════════════════════════════════════════════════════════════════
# PHASE 16: Triple interaction rules
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 16: TRIPLE INTERACTION (3-feature combinations)")
print("=" * 90)

# Focus on most promising features
key_features = ['ct_ka', 'sv_az', 'sv_ka', 'kw_az', 'kw_ka', 'ka_row', 'ka_col', 'pos', 'col']

perfect_triples = []
for f1 in key_features:
    for f2 in key_features:
        for f3 in key_features:
            if f1 == f2 or f1 == f3 or f2 == f3:
                continue
            for M in [2, 3, 5, 7, 13]:
                # (f1 + f2 + f3) mod M
                null_res = set((features[p][f1] + features[p][f2] + features[p][f3]) % M
                             for p in null_palette)
                nonnull_res = set((features[p][f1] + features[p][f2] + features[p][f3]) % M
                                for p in nonnull_palette)
                if not (null_res & nonnull_res):
                    desc = f"({f1}+{f2}+{f3}) % {M}: null∈{sorted(null_res)}, nonnull∈{sorted(nonnull_res)}"
                    perfect_triples.append(desc)

                # (f1 + f2 - f3) mod M
                null_res = set((features[p][f1] + features[p][f2] - features[p][f3]) % M
                             for p in null_palette)
                nonnull_res = set((features[p][f1] + features[p][f2] - features[p][f3]) % M
                                for p in nonnull_palette)
                if not (null_res & nonnull_res):
                    desc = f"({f1}+{f2}-{f3}) % {M}: null∈{sorted(null_res)}, nonnull∈{sorted(nonnull_res)}"
                    perfect_triples.append(desc)

                # (f1 * f2 + f3) mod M
                null_res = set((features[p][f1] * features[p][f2] + features[p][f3]) % M
                             for p in null_palette)
                nonnull_res = set((features[p][f1] * features[p][f2] + features[p][f3]) % M
                                for p in nonnull_palette)
                if not (null_res & nonnull_res):
                    desc = f"({f1}*{f2}+{f3}) % {M}: null∈{sorted(null_res)}, nonnull∈{sorted(nonnull_res)}"
                    perfect_triples.append(desc)

if perfect_triples:
    print(f"\n  PERFECT TRIPLE RULES: {len(perfect_triples)}")
    # Deduplicate
    seen = set()
    for desc in perfect_triples:
        if desc not in seen:
            seen.add(desc)
            print(f"    {desc}")
        if len(seen) >= 50:
            print(f"    ... and {len(perfect_triples) - 50} more")
            break
else:
    print(f"\n  No perfect triple rules found.")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 17: Pure position-based rules (distance from special positions)
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 17: DISTANCE-BASED AND SPECIAL POSITION RULES")
print("=" * 90)

# Distance from crib starts
ENE_START = 21
BCL_START = 63

for center_name, center in [("ENE_start(21)", 21), ("BCL_start(63)", 63),
                              ("ENE_end(33)", 33), ("BCL_end(73)", 73),
                              ("CT_center(48)", 48), ("W_positions", None)]:
    if center is not None:
        for M in [2,3,5,7,13,26]:
            null_res = set(abs(p - center) % M for p in null_palette)
            nonnull_res = set(abs(p - center) % M for p in nonnull_palette)
            if not (null_res & nonnull_res):
                print(f"  PERFECT: |pos - {center_name}| mod {M}: null={sorted(null_res)}, nonnull={sorted(nonnull_res)}")

# W positions as markers
W_POS = [20, 36, 48, 58, 74]
for p in palette_positions:
    min_w_dist = min(abs(p - w) for w in W_POS)
    features[p]['min_w_dist'] = min_w_dist

for M in [2,3,5,7,13]:
    null_res = set(features[p]['min_w_dist'] % M for p in null_palette)
    nonnull_res = set(features[p]['min_w_dist'] % M for p in nonnull_palette)
    if not (null_res & nonnull_res):
        print(f"  PERFECT: min_W_distance mod {M}: null={sorted(null_res)}, nonnull={sorted(nonnull_res)}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 18: Neighbor-based rules
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 18: NEIGHBOR-BASED RULES")
print("=" * 90)

# null iff both neighbors are non-palette (or other neighbor conditions)
for p in palette_positions:
    left_pal = CT[p-1] in PALETTE if p > 0 else False
    right_pal = CT[p+1] in PALETTE if p < CT_LEN-1 else False
    left_null = (p-1) in CONSENSUS_NULLS if p > 0 else False
    right_null = (p+1) in CONSENSUS_NULLS if p < CT_LEN-1 else False
    left_char_az = AZ_IDX[CT[p-1]] if p > 0 else -1
    right_char_az = AZ_IDX[CT[p+1]] if p < CT_LEN-1 else -1

    features[p]['left_pal'] = left_pal
    features[p]['right_pal'] = right_pal
    features[p]['left_null'] = left_null
    features[p]['right_null'] = right_null
    features[p]['neighbor_pal_count'] = int(left_pal) + int(right_pal)

# null iff neighbor count == some value
for nc in [0, 1, 2]:
    pred_null = set(p for p in palette_positions if features[p]['neighbor_pal_count'] == nc)
    acc, tp, fp, fn, tn = score_rule(pred_null)
    print(f"  neighbor_pal_count == {nc}: acc={acc}/35 (tp={tp}, fp={fp}, fn={fn}, tn={tn})")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 19: (pos%7, pos%5) CELL ANALYSIS — DETAILED
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 19: (pos%7, pos%5) CELL DETAILED ANALYSIS")
print("=" * 90)

# Build the 7x5 table
print("\n7x5 table of palette positions (pos%7 = column, pos%5 = row):")
print(f"{'':>8}", end="")
for c5 in range(5):
    print(f"  p%5={c5:>2}", end="")
print()

all_cells = {}
for c7 in range(7):
    print(f"p%7={c7}:", end="")
    for c5 in range(5):
        positions = [p for p in palette_positions if p % 7 == c7 and p % 5 == c5]
        null_here = [p for p in positions if labels[p]]
        nonnull_here = [p for p in positions if not labels[p]]
        all_cells[(c7,c5)] = (null_here, nonnull_here)
        if not positions:
            print(f"{'---':>8}", end="")
        else:
            # Show as N=null count, R=real count
            marker = ""
            if null_here and not nonnull_here: marker = "*"  # pure null
            elif nonnull_here and not null_here: marker = "."  # pure real
            else: marker = "?"  # mixed
            print(f"  {len(null_here)}N{len(nonnull_here)}R{marker}", end="")
    print()

# Count mixed cells
mixed = [(c7,c5) for (c7,c5), (n, nn) in all_cells.items() if n and nn]
pure_null_cells = [(c7,c5) for (c7,c5), (n, nn) in all_cells.items() if n and not nn]
pure_real_cells = [(c7,c5) for (c7,c5), (n, nn) in all_cells.items() if nn and not n]
empty_cells = [(c7,c5) for (c7,c5), (n, nn) in all_cells.items() if not n and not nn]

print(f"\nPure null cells: {pure_null_cells}")
print(f"Pure real cells: {pure_real_cells}")
print(f"Mixed cells: {mixed}")
print(f"Empty cells (no palette): {len(empty_cells)}")

# If there are few mixed cells, analyze what distinguishes within them
for c7, c5 in mixed:
    null_pos, nonnull_pos = all_cells[(c7,c5)]
    print(f"\nMixed cell ({c7},{c5}):")
    for p in null_pos + nonnull_pos:
        row, col = k4_to_grid(p)
        label = "NULL" if labels[p] else "REAL"
        print(f"  p={p:>2} CT={CT[p]} row={row} col={col:>2} {label}")

# ══════════════════════════════════════════════════════════════════════════
# PHASE 20: THE GLOBAL BEST RULES SUMMARY
# ══════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 90)
print("PHASE 20: GLOBAL SUMMARY — TOP RULES BY ACCURACY")
print("=" * 90)

# Collect all rules tested so far and their accuracies
# We already have all_rules from Phase 1, perfect/near-perfect from Phase 15/16

# Compute a summary of the best approach
print(f"\nConsensus null positions: {sorted(CONSENSUS_NULLS)}")
print(f"Consensus null palette chars: {''.join(CT[p] for p in null_palette)}")
print(f"Non-null palette chars: {''.join(CT[p] for p in nonnull_palette)}")

# Final: check the KA-Polybius "row parity" approach
# On the 5-wide KA grid, palette letters are at (row, col) where col in {0,3}
# Row values: K=row0, O=row1, B=row1, G=row2, I=row3, W=row4, Z=row5
print("\n--- KA Polybius row for each palette position ---")
for p in palette_positions:
    ka_idx = KA_IDX[CT[p]]
    ka_row = ka_idx // 5
    ka_col = ka_idx % 5
    label = "NULL" if labels[p] else "    "
    print(f"  p={p:>2} CT={CT[p]} KA_row={ka_row} KA_col={ka_col} "
          f"pos%7={p%7} pos%5={p%5} p%35={p%35:>2} {label}")

# null iff (ka_row + pos) mod something?
for M in [2,3,5,6,7]:
    null_res = set((KA_IDX[CT[p]]//5 + p) % M for p in null_palette)
    nonnull_res = set((KA_IDX[CT[p]]//5 + p) % M for p in nonnull_palette)
    if not (null_res & nonnull_res):
        print(f"  PERFECT: (KA_row + pos) mod {M}: null={sorted(null_res)}, nonnull={sorted(nonnull_res)}")

# null iff (ka_col==0 AND pos<X) OR (ka_col==3 AND pos>Y)?
# ka_col is always 0 or 3 for palette
col0_palette = [p for p in palette_positions if KA_IDX[CT[p]] % 5 == 0]
col3_palette = [p for p in palette_positions if KA_IDX[CT[p]] % 5 == 3]
print(f"\n  Palette KA_col=0 ({len(col0_palette)} positions): {col0_palette}")
print(f"    Null: {[p for p in col0_palette if labels[p]]}")
print(f"    Non-null: {[p for p in col0_palette if not labels[p]]}")
print(f"  Palette KA_col=3 ({len(col3_palette)} positions): {col3_palette}")
print(f"    Null: {[p for p in col3_palette if labels[p]]}")
print(f"    Non-null: {[p for p in col3_palette if not labels[p]]}")

# Within col0: what separates null from non-null?
print(f"\n  Within KA_col=0 (letters K,O,I,Z,D,Q):")
for p in col0_palette:
    label = "NULL" if labels[p] else "REAL"
    row, col = k4_to_grid(p)
    print(f"    p={p:>2} CT={CT[p]} KA_row={KA_IDX[CT[p]]//5} pos%7={p%7} pos%5={p%5} col={col:>2} {label}")

print(f"\n  Within KA_col=3 (letters B,G,W,M,P):")  # M,P are not in palette
for p in col3_palette:
    label = "NULL" if labels[p] else "REAL"
    row, col = k4_to_grid(p)
    print(f"    p={p:>2} CT={CT[p]} KA_row={KA_IDX[CT[p]]//5} pos%7={p%7} pos%5={p%5} col={col:>2} {label}")

# ══════════════════════════════════════════════════════════════════════════
# FINAL: Write results
# ══════════════════════════════════════════════════════════════════════════

output_path = os.path.join(os.path.dirname(__file__), '..', '..', 'results',
                          'palette_position_rule_hunt.json')
output_path = os.path.abspath(output_path)

summary = {
    'timestamp': datetime.now(timezone.utc).isoformat(),
    'palette': sorted(PALETTE),
    'palette_positions': palette_positions,
    'null_palette': null_palette,
    'nonnull_palette': nonnull_palette,
    'perfect_linear_rules': len(best_linear),
    'perfect_mixed_rules_ka': len(best_mixed),
    'perfect_mixed_rules_az': len(best_mixed_az),
    'perfect_dual_feature_rules': len(perfect_rules_phase15),
    'perfect_triple_rules': len(perfect_triples),
    'mixed_cells_7x5': len(mixed),
    'pure_null_cells_7x5': len(pure_null_cells),
    'pure_real_cells_7x5': len(pure_real_cells),
}

with open(output_path, 'w') as f:
    json.dump(summary, f, indent=2)

print(f"\n\nResults written to: {output_path}")
print("DONE.")
