#!/usr/bin/env python3 -u
"""
Cipher: Sculpture reading paths
Family: campaigns
Status: active
Keyspace: ~415K paths × 4 variants × variable offsets
Last run:
Best score:

Exhaustive Sculpture Reading Path Search v1

Hypothesis: the cipher KEY for K4 is generated by reading characters from the
Kryptos sculpture surfaces (tableau, cipher grid, plaintext grid) in a specific
path or order. We enumerate all plausible reading paths and test each as a
cipher key under 4 decryption variants.

Families:
  1. Linear paths on the 26x26 Quagmire II tableau (~50K paths)
  2. Linear paths on the 28x31 master grid (~200K paths)
  3. Keyword-parameterized paths (~100K paths)
  4. Coordinate-parameterized paths (~10K paths)
  5. Compound paths: surface-indexes-surface, dual-path Polybius,
     chained transformation, position-mapped reads (~50K paths)
  6. Morse and physical features: NDYAHR/KRYPTOS/SEVEN skip patterns (~5K paths)
"""

import sys
import os
import time
import json
import argparse
from collections import Counter
from itertools import product
from multiprocessing import Pool, cpu_count

_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(_ROOT, "src"))

from kryptos.kernel.constants import (
    CT, CT_LEN, ALPH, ALPH_IDX, MOD, CRIB_DICT, KRYPTOS_ALPHABET,
)

# ── Kryptos Alphabet ────────────────────────────────────────────────────────

KA = KRYPTOS_ALPHABET
KA_IDX = {c: i for i, c in enumerate(KA)}
CRIB_POS = sorted(CRIB_DICT.keys())

# ── Report threshold (overridable via CLI) ──────────────────────────────────

THRESHOLD = 12

# ══════════════════════════════════════════════════════════════════════════════
# SURFACE 1: QUAGMIRE II TABLEAU (26×26)
# ══════════════════════════════════════════════════════════════════════════════

TABLEAU = [[KA[(r + c) % 26] for c in range(26)] for r in range(26)]
TABLEAU_FLAT = ''.join(''.join(row) for row in TABLEAU)  # 676 chars

# ══════════════════════════════════════════════════════════════════════════════
# SURFACE 2: MASTER CIPHERTEXT GRID (28×31)
# ══════════════════════════════════════════════════════════════════════════════

# Full sculpture ciphertext (869 chars with squeezed ? at position 288)
_FULL_CT_869 = (
    "EMUFPHZLRFAXYUSDJKZLDKRNSHGNFIVJ"
    "YQTQUXQBQVYUVLLTREVJYQTMKYRDMFD"
    "VFPJUDEEHZWETZYVGWHKKQETGFQJNCE"
    "GGWHKK?DQMCPFQZDQMMIAGPFXHQRLG"
    "TIMVMZJANQLVKQEDAGDVFRPJUNGEUNA"
    "QZGZLECGYUXUEENJTBJLBQCRTBJDFHRR"
    "YIZETKZEMVDUFKSJHKFWHKUWQLSZFTI"
    "HHDDDUVH?DWKBFUFPWNTDFIYCUQZERE"
    "EVLDKFEZMOQQJLTTUGSYQPFEUNLAVIDX"
    "FLGGTEZ?FKZBSFDQVGOGIPUFXHHDRKF"
    "FHQNTGPUAECNUVPDJMQCLQUMUNEDFQ"
    "ELZZVRRGKFFVOEEXBDMVPNFQXEZLGRE"
    "DNQFMPNZGLFLPMRJQYALMGNUVPDXVKP"
    "DQUMEBEDMHDAFMJGZNUPLGEWJLLAETG"
    "ENDYAHROHNLSRHEOCPTEOIBIDYSHNAIA"
    "CHTNREYULDSLLSLLNOHSNOSMRWXMNE"
    "TPRNGATIHNRARPESLNNELEBLPIIACAE"
    "WMTWNDITEENRAHCTENEUDRETNHAEOE"
    "TFOLSEDTIWENHAEIOYTEYQHEENCTAYCR"
    "EIFTBRSPAMHHEWENATAMATEGYEERLB"
    "TEEFOASFIOTUETUAEOTOARMAEERTNRTI"
    "BSEDDNIAAHTTMSTEWPIEROAGRIEWFEB"
    "AECTDDHILCEIHSITEGOEAOSDDRYDLORIT"
    "RKLMLEHAGTDHARDPNEOHMGFMFEUHE"
    "ECDMRIPFEIMEHNLSSTTRTVDOHW?OBKR"
    "UOXOGHULBSOLIFBBWFLRVQQPRNGKSSO"
    "TWTQSJQSSEKZZWATJKLUDIAWINFBNYP"
    "VTTMZFPKWGDKZXTJCDIGKUHUAUEKCAR"
)

# Remove squeezed ? at position 288 to get the 868-char grid
_SQUEEZED_POS = 288
assert _FULL_CT_869[_SQUEEZED_POS] == '?'
_CIPHER_GRID_868 = _FULL_CT_869[:_SQUEEZED_POS] + _FULL_CT_869[_SQUEEZED_POS + 1:]
assert len(_CIPHER_GRID_868) == 868

# Replace remaining ? marks (section breaks) with X for uniformity
# Positions in 868-char string: 100, 226, 770
MASTER_CT_FLAT = _CIPHER_GRID_868.replace('?', 'X')
assert len(MASTER_CT_FLAT) == 868
assert MASTER_CT_FLAT.isalpha()

GRID_WIDTH = 31
GRID_ROWS = 28
MASTER_CT = [MASTER_CT_FLAT[i * GRID_WIDTH:(i + 1) * GRID_WIDTH] for i in range(GRID_ROWS)]

# Alpha-only version (865 chars, no section markers)
MASTER_CT_ALPHA = ''.join(c for c in _CIPHER_GRID_868 if c.isalpha())

# ══════════════════════════════════════════════════════════════════════════════
# SURFACE 3: MASTER PLAINTEXT GRID
# ══════════════════════════════════════════════════════════════════════════════

K1_PT = "BETWEENSUBTLESHADINGANDTHEABSENCEOFLIGHTLIESTHENUANCEOFIQLUSION"
K2_PT = (
    "ITWASTOTALLYINVISIBLEHOWSTHATPOSSIBLETHEYUSEDTHEEARTHSMAGNETICFIELD"
    "XTHEINFORMATIONWASGATHEREDANDTRANSMITTEDUNDERGRUUNDTOANUNKNOWNLOCATION"
    "XDOESLANGLEYKNOWABOUTTHISTHEYSHOULDITSBURIEDOUTTHERESOMEWHEREXWHOKNOWS"
    "THEEXACTLOCATIONONLYWWTHISWASHISLASTMESSAGEXTHIRTYEIGHTDEGREESFIFTY"
    "SEVENMINUTESSIXPOINTFIVESECONDSNORTHSEVENTYSEVENDEGREESEIGHTMINUTESFORTY"
    "FOURSECONDSWESTIDBYROWS"
)
K3_PT = (
    "SLOWLYDESPARATLYSLOWLYTHEREMAINSOFPASSAGEDEBRISTHATENCUMBEREDTHELOWERPART"
    "OFTHEDOORWAYWASREMOVEDWITHTREMBLINGHANDSIMADEATINYBREACHINTHEUPPERLEFTHAND"
    "CORNERANDTHENWIDENINGTHEHOLEALITTLEIINSERTEDTHECANDLEANDPEABOREDINTHOHOTAIR"
    "ESCAPINGFROMTHECHAMBERCAUSEDTHEFLAMETOFLICKERBUTPRESENTLYDETAILSOFTHEROOMWITHIN"
    "EMERGEDFROMTHEMISTXCANYOUSEEANYTHINGQ"
)

# Sanitize plaintexts (uppercase alpha only)
def _sanitize(s):
    return ''.join(c for c in s.upper() if c.isalpha())

K1_PT_CLEAN = _sanitize(K1_PT)
K2_PT_CLEAN = _sanitize(K2_PT)
K3_PT_CLEAN = _sanitize(K3_PT)

# For the master PT grid, substitute PT where we have it (K1-K3),
# and keep CT for K4 (unknown). Match lengths to the grid.
# K1 CT = 63, K2 CT = 369, K3 CT = 336, K4 CT = 97
# Total alpha = 865, but grid = 868 (3 section markers)
# We'll build the flat PT string matching the 868-char grid structure
# Section markers at positions 100, 226, 770 in the 868-char grid

# Build alpha-only PT
_PT_ALPHA = K1_PT_CLEAN + K2_PT_CLEAN + K3_PT_CLEAN
# Pad/trim to match K1+K2+K3 alpha length (63+369+336=768)
_K123_ALPHA_LEN = 63 + 369 + 336  # 768
_PT_ALPHA = _PT_ALPHA[:_K123_ALPHA_LEN]
if len(_PT_ALPHA) < _K123_ALPHA_LEN:
    _PT_ALPHA += 'A' * (_K123_ALPHA_LEN - len(_PT_ALPHA))

# For K4, we don't have PT, so use CT as placeholder
_PT_ALPHA_FULL = _PT_ALPHA + CT  # 768 + 97 = 865

# Now rebuild with section markers at the right positions
# In the 868-char grid, section markers are at positions 100, 226, 770
# These correspond to: after K1 (63 alpha), within K2, within K2, between K3/K4
# Actually, let's just build it more carefully
# The 868-grid has ? at positions 100, 226, 770 in the original
# Let's map: position in 868 -> alpha index
_pt_868 = []
_alpha_idx = 0
for i in range(868):
    if _CIPHER_GRID_868[i] == '?':
        _pt_868.append('X')  # section marker
    else:
        if _alpha_idx < len(_PT_ALPHA_FULL):
            _pt_868.append(_PT_ALPHA_FULL[_alpha_idx])
        else:
            _pt_868.append('A')
        _alpha_idx += 1
MASTER_PT_FLAT = ''.join(_pt_868)
assert len(MASTER_PT_FLAT) == 868
MASTER_PT = [MASTER_PT_FLAT[i * GRID_WIDTH:(i + 1) * GRID_WIDTH] for i in range(GRID_ROWS)]

# ══════════════════════════════════════════════════════════════════════════════
# SURFACE 4: MORSE TEXT (from Copperplate side)
# ══════════════════════════════════════════════════════════════════════════════

# Morse code on the copperplate (Sanborn's other element)
# This is the commonly cited decoding
MORSE_TEXT = _sanitize(
    "VIRTUALLYINVISIBLEDIGITALLYTYOURSEOSTWHATDOESITMEAN"
    "SOSTYOUHAVETOFINDTHECRYPTOSFANNOTEONLYISPELLTHESECRETOUTHEREBETWEENSUBTLE"
)

# ══════════════════════════════════════════════════════════════════════════════
# SCORER
# ══════════════════════════════════════════════════════════════════════════════

def score_key(key_chars):
    """Test key_chars as cipher key under 4 variants.

    For keys shorter than 97, cycle them.
    Returns list of (score, variant_name).
    """
    if not key_chars:
        return []

    key_upper = key_chars.upper()
    key_len = len(key_upper)
    hits = []

    for variant_name, decrypt_func in [
        ('beau_az', lambda ct_c, k_c: (ALPH_IDX[k_c] - ALPH_IDX[ct_c]) % 26),
        ('vig_az', lambda ct_c, k_c: (ALPH_IDX[ct_c] - ALPH_IDX[k_c]) % 26),
        ('beau_ka', lambda ct_c, k_c: (KA_IDX[k_c] - KA_IDX[ct_c]) % 26),
        ('vig_ka', lambda ct_c, k_c: (KA_IDX[ct_c] - KA_IDX[k_c]) % 26),
    ]:
        score = 0
        for pos in CRIB_POS:
            key_idx = pos % key_len
            k_c = key_upper[key_idx]
            if k_c not in ALPH_IDX:
                continue
            pt_val = decrypt_func(CT[pos], k_c)
            if variant_name.endswith('_ka'):
                pt_char = KA[pt_val]
            else:
                pt_char = ALPH[pt_val]
            if pt_char == CRIB_DICT[pos]:
                score += 1
        if score >= THRESHOLD:
            hits.append((score, variant_name))
    return hits


def test_path(key_chars, desc, family, hits_list):
    """Score a key at all valid offsets (for long keys) or cycled (for short).

    Appends any hits >= THRESHOLD to hits_list. Returns number of tests run.
    """
    if not key_chars:
        return 0

    tests = 0
    klen = len(key_chars)

    if klen >= 97:
        # Sliding window: test every 97-char window
        for offset in range(klen - 96):
            window = key_chars[offset:offset + 97]
            results = score_key(window)
            tests += 1
            for score, variant in results:
                hits_list.append({
                    'score': score, 'variant': variant,
                    'family': family, 'desc': desc,
                    'offset': offset, 'key_preview': window[:30],
                })
                if score >= 18:
                    print(f'  *** SIGNAL: {score}/24 {variant} {desc} offset={offset}',
                          flush=True)
    else:
        # Short key: cycle it
        results = score_key(key_chars)
        tests += 1
        for score, variant in results:
            hits_list.append({
                'score': score, 'variant': variant,
                'family': family, 'desc': desc,
                'offset': 0, 'key_preview': key_chars[:30],
            })
            if score >= 18:
                print(f'  *** SIGNAL: {score}/24 {variant} {desc}', flush=True)

    return tests


# ══════════════════════════════════════════════════════════════════════════════
# PATH GENERATORS
# ══════════════════════════════════════════════════════════════════════════════

# ── Family 1: Linear paths on the 26×26 Tableau ─────────────────────────────

def _read_grid_rows(grid, nrows, ncols, mode='lr', start_row=0):
    """Read a grid row-by-row with specified mode.

    mode: 'lr' = left-to-right, 'rl' = right-to-left, 'boustro' = alternating
    start_row: which row to start from (wraps around)
    """
    chars = []
    for i in range(nrows):
        r = (start_row + i) % nrows
        row = grid[r]
        row_str = row if isinstance(row, str) else ''.join(row)
        if mode == 'lr':
            chars.append(row_str)
        elif mode == 'rl':
            chars.append(row_str[::-1])
        elif mode == 'boustro':
            if i % 2 == 0:
                chars.append(row_str)
            else:
                chars.append(row_str[::-1])
    return ''.join(chars)


def _read_grid_cols(grid, nrows, ncols, mode='tb', start_col=0):
    """Read a grid column-by-column.

    mode: 'tb' = top-to-bottom, 'bt' = bottom-to-top, 'boustro' = alternating
    """
    chars = []
    for j in range(ncols):
        c = (start_col + j) % ncols
        col_chars = []
        for r in range(nrows):
            row = grid[r]
            row_str = row if isinstance(row, str) else ''.join(row)
            if c < len(row_str):
                col_chars.append(row_str[c])
        col_str = ''.join(col_chars)
        if mode == 'tb':
            chars.append(col_str)
        elif mode == 'bt':
            chars.append(col_str[::-1])
        elif mode == 'boustro':
            if j % 2 == 0:
                chars.append(col_str)
            else:
                chars.append(col_str[::-1])
    return ''.join(chars)


def _read_diagonal(flat, nrows, ncols, dr, dc, start_r, start_c):
    """Read a diagonal path through a grid (with wrapping).

    Returns nrows*ncols chars by stepping (dr, dc) with mod wrapping.
    """
    total = nrows * ncols
    chars = []
    r, c = start_r, start_c
    visited = set()
    for _ in range(total):
        idx = r * ncols + c
        if idx in visited:
            break
        visited.add(idx)
        chars.append(flat[idx])
        r = (r + dr) % nrows
        c = (c + dc) % ncols
    return ''.join(chars)


def _read_spiral(grid, nrows, ncols, clockwise=True, start_corner=0):
    """Read a grid in spiral order.

    start_corner: 0=top-left, 1=top-right, 2=bottom-right, 3=bottom-left
    """
    # Build flat matrix for indexing
    mat = []
    for r in range(nrows):
        row = grid[r]
        row_str = row if isinstance(row, str) else ''.join(row)
        mat.append(list(row_str))

    # Transform so top-left is always the start corner
    # Then read spiral, then the result is the same regardless
    if start_corner == 1:
        # Flip horizontally
        mat = [row[::-1] for row in mat]
    elif start_corner == 2:
        # Flip both
        mat = [row[::-1] for row in mat[::-1]]
    elif start_corner == 3:
        # Flip vertically
        mat = mat[::-1]

    if not clockwise:
        # Transpose for counter-clockwise
        new_mat = []
        for c in range(len(mat[0]) if mat else 0):
            new_mat.append([mat[r][c] for r in range(len(mat))])
        mat = new_mat
        nrows, ncols = ncols, nrows

    # Standard CW spiral from top-left
    chars = []
    top, bottom, left, right = 0, len(mat) - 1, 0, (len(mat[0]) - 1 if mat else 0)
    while top <= bottom and left <= right:
        for c in range(left, right + 1):
            chars.append(mat[top][c])
        top += 1
        for r in range(top, bottom + 1):
            chars.append(mat[r][right])
        right -= 1
        if top <= bottom:
            for c in range(right, left - 1, -1):
                chars.append(mat[bottom][c])
            bottom -= 1
        if left <= right:
            for r in range(bottom, top - 1, -1):
                chars.append(mat[r][left])
            left += 1

    return ''.join(chars)


def gen_family_1():
    """Yield (key_chars, description) for all Family 1 paths on the 26x26 tableau."""
    nrows, ncols = 26, 26

    # 1. Row reads: 3 modes × 26 start rows = 78
    for mode in ('lr', 'rl', 'boustro'):
        for sr in range(nrows):
            key = _read_grid_rows(TABLEAU, nrows, ncols, mode, sr)
            yield key, f"tab_rows_{mode}_start{sr}"

    # 2. Column reads: 3 modes × 26 start cols = 78
    for mode in ('tb', 'bt', 'boustro'):
        for sc in range(ncols):
            key = _read_grid_cols(TABLEAU, nrows, ncols, mode, sc)
            yield key, f"tab_cols_{mode}_start{sc}"

    # 3. Diagonals: 4 directions × starting edges
    diag_dirs = [
        (1, 1, "SE"),    # ↘
        (1, -1, "SW"),   # ↙
        (-1, 1, "NE"),   # ↗
        (-1, -1, "NW"),  # ↖
    ]
    for dr, dc, name in diag_dirs:
        # Start from top edge (row 0, all cols) and left edge (all rows, col 0)
        starts = set()
        for c in range(ncols):
            starts.add((0, c))
        for r in range(nrows):
            starts.add((r, 0))
        for sr, sc in sorted(starts):
            key = _read_diagonal(TABLEAU_FLAT, nrows, ncols, dr, dc, sr, sc)
            if len(key) >= 2:
                yield key, f"tab_diag_{name}_from({sr},{sc})"

    # 4. Spirals: CW and CCW from 4 corners = 8
    for cw in (True, False):
        for corner in range(4):
            key = _read_spiral(TABLEAU, nrows, ncols, cw, corner)
            cw_str = "CW" if cw else "CCW"
            yield key, f"tab_spiral_{cw_str}_corner{corner}"

    # 5. Skip-N on flat tableau: N=2..13, offsets 0..N-1, row-major + col-major
    # Row-major flat
    for skip_n in range(2, 14):
        for offset in range(skip_n):
            key = TABLEAU_FLAT[offset::skip_n]
            if key:
                yield key, f"tab_skip{skip_n}_rowmaj_off{offset}"

    # Column-major flat
    col_major = _read_grid_cols(TABLEAU, nrows, ncols, 'tb', 0)
    for skip_n in range(2, 14):
        for offset in range(skip_n):
            key = col_major[offset::skip_n]
            if key:
                yield key, f"tab_skip{skip_n}_colmaj_off{offset}"


# ── Family 2: Linear paths on the Master Grid ───────────────────────────────

def gen_family_2():
    """Yield (key_chars, description) for Family 2 paths on the 28x31 grids."""
    surfaces = [
        ("mct", MASTER_CT, MASTER_CT_FLAT),
        ("mpt", MASTER_PT, MASTER_PT_FLAT),
    ]

    for surf_name, grid, flat in surfaces:
        nrows, ncols = GRID_ROWS, GRID_WIDTH

        # Row reads: 3 modes × 28 start rows
        for mode in ('lr', 'rl', 'boustro'):
            for sr in range(nrows):
                key = _read_grid_rows(grid, nrows, ncols, mode, sr)
                yield key, f"{surf_name}_rows_{mode}_start{sr}"

        # Column reads: 3 modes × 31 start cols
        for mode in ('tb', 'bt', 'boustro'):
            for sc in range(ncols):
                key = _read_grid_cols(grid, nrows, ncols, mode, sc)
                yield key, f"{surf_name}_cols_{mode}_start{sc}"

        # Diagonals: 4 directions from top and left edges
        diag_dirs = [
            (1, 1, "SE"), (1, -1, "SW"), (-1, 1, "NE"), (-1, -1, "NW"),
        ]
        for dr, dc, dname in diag_dirs:
            starts = set()
            for c in range(ncols):
                starts.add((0, c))
            for r in range(nrows):
                starts.add((r, 0))
            for sr, sc in sorted(starts):
                key = _read_diagonal(flat, nrows, ncols, dr, dc, sr, sc)
                if len(key) >= 2:
                    yield key, f"{surf_name}_diag_{dname}_from({sr},{sc})"

        # Spirals: 8 paths per surface
        for cw in (True, False):
            for corner in range(4):
                key = _read_spiral(grid, nrows, ncols, cw, corner)
                cw_str = "CW" if cw else "CCW"
                yield key, f"{surf_name}_spiral_{cw_str}_corner{corner}"

        # Skip-N on flat: N=2..13
        for skip_n in range(2, 14):
            for offset in range(skip_n):
                key = flat[offset::skip_n]
                if key:
                    yield key, f"{surf_name}_skip{skip_n}_off{offset}"

        # Column-major skip
        col_major = _read_grid_cols(grid, nrows, ncols, 'tb', 0)
        for skip_n in range(2, 14):
            for offset in range(skip_n):
                key = col_major[offset::skip_n]
                if key:
                    yield key, f"{surf_name}_colskip{skip_n}_off{offset}"

    # Single-column reads from master CT grid (28-char keys, cycled)
    for c in range(GRID_WIDTH):
        col = ''.join(MASTER_CT[r][c] for r in range(GRID_ROWS))
        yield col, f"mct_singlecol{c}"
        # Also reversed
        yield col[::-1], f"mct_singlecol{c}_rev"

    # Same for PT grid
    for c in range(GRID_WIDTH):
        col = ''.join(MASTER_PT[r][c] for r in range(GRID_ROWS))
        yield col, f"mpt_singlecol{c}"
        yield col[::-1], f"mpt_singlecol{c}_rev"

    # K1-K3 region only (first 771 chars of master CT, before K4)
    k123_ct = MASTER_CT_FLAT[:771]
    yield k123_ct, "k123ct_flat"
    yield k123_ct[::-1], "k123ct_flat_rev"

    # K1-K3 PT region
    k123_pt = MASTER_PT_FLAT[:771]
    yield k123_pt, "k123pt_flat"
    yield k123_pt[::-1], "k123pt_flat_rev"

    # Alpha-only master CT (no section markers)
    yield MASTER_CT_ALPHA, "mct_alpha"
    yield MASTER_CT_ALPHA[::-1], "mct_alpha_rev"

    # Morse text
    if MORSE_TEXT:
        yield MORSE_TEXT, "morse_flat"
        yield MORSE_TEXT[::-1], "morse_flat_rev"


# ── Family 3: Keyword-Parameterized paths ───────────────────────────────────

KEYWORDS = [
    "KRYPTOS", "SEVEN", "PALIMPSEST", "ABSCISSA", "DEFECTOR",
    "KOMPASS", "HOROLOGE", "BERLIN", "CARTER", "SANBORN",
    "SHADOW", "ENIGMA", "URANIA", "QUARTZ",
]


def gen_family_3():
    """Yield (key_chars, description) for keyword-parameterized paths."""
    surfaces = [
        ("tab", TABLEAU, TABLEAU_FLAT, 26, 26),
        ("mct", MASTER_CT, MASTER_CT_FLAT, GRID_ROWS, GRID_WIDTH),
        ("mpt", MASTER_PT, MASTER_PT_FLAT, GRID_ROWS, GRID_WIDTH),
    ]

    for kw in KEYWORDS:
        kw_len = len(kw)

        for surf_name, grid, flat, nrows, ncols in surfaces:
            surf_len = len(flat)

            # 1. Row-select: key[i] = grid[KA_IDX[kw[i%kwlen]] % nrows][i % ncols]
            key_chars = []
            for i in range(max(97, ncols * kw_len)):
                r = KA_IDX[kw[i % kw_len]] % nrows
                c = i % ncols
                key_chars.append(grid[r][c])
            yield ''.join(key_chars), f"{surf_name}_rowsel_{kw}"

            # 2. Col-select: key[i] = grid[i % nrows][KA_IDX[kw[i%kwlen]] % ncols]
            key_chars = []
            for i in range(max(97, nrows * kw_len)):
                r = i % nrows
                c = KA_IDX[kw[i % kw_len]] % ncols
                key_chars.append(grid[r][c])
            yield ''.join(key_chars), f"{surf_name}_colsel_{kw}"

            # 3. Skip: read flat, skip by KA_IDX[kw[i%kwlen]]+1 each step
            key_chars = []
            pos = 0
            for i in range(200):
                key_chars.append(flat[pos % surf_len])
                skip = KA_IDX[kw[i % kw_len]] + 1
                pos += skip
            yield ''.join(key_chars), f"{surf_name}_kwskip_{kw}"

            # 4. Offset: key[i] = flat[(i + KA_IDX[kw[i%kwlen]]) % surf_len]
            key_chars = []
            for i in range(200):
                idx = (i + KA_IDX[kw[i % kw_len]]) % surf_len
                key_chars.append(flat[idx])
            yield ''.join(key_chars), f"{surf_name}_kwoff_{kw}"

            # 5. Row-then-col: row = KA_IDX[kw[i%kwlen]], col = KA_IDX[kw[(i+1)%kwlen]]
            key_chars = []
            for i in range(200):
                r = KA_IDX[kw[i % kw_len]] % nrows
                c = KA_IDX[kw[(i + 1) % kw_len]] % ncols
                key_chars.append(grid[r][c])
            yield ''.join(key_chars), f"{surf_name}_rc_{kw}"

            # 6. Keyword as cycling key directly (Quagmire lookup for tableau)
            if surf_name == "tab":
                # Use keyword letters to select rows, read column = position
                key_chars = []
                for i in range(200):
                    r = KA_IDX[kw[i % kw_len]]
                    c = i % ncols
                    key_chars.append(TABLEAU[r][c])
                yield ''.join(key_chars), f"tab_quag_{kw}"

                # Also: column = keyword letter, row = position
                key_chars = []
                for i in range(200):
                    r = i % nrows
                    c = KA_IDX[kw[i % kw_len]]
                    key_chars.append(TABLEAU[r][c])
                yield ''.join(key_chars), f"tab_quag_col_{kw}"

        # Keyword used directly as repeating key (for completeness)
        yield kw, f"kw_direct_{kw}"
        # Keyword reversed
        yield kw[::-1], f"kw_direct_{kw}_rev"


# ── Family 4: Coordinate-Parameterized paths ────────────────────────────────

def gen_family_4():
    """Yield (key_chars, description) for coordinate-parameterized paths."""
    number_sets = {
        "k2":       [38, 57, 6, 77, 8, 44],
        "tomb":     [25, 44, 25, 32, 36, 5],
        "sums":     [63, 101, 32, 109, 44, 49],
        "digitsums": [7, 8, 17, 5, 9, 11],
        "k2_raw":   [38, 57, 6, 5, 77, 8, 44],   # with 6.5 → 6, 5
        "grid":     [28, 31, 14, 24, 8, 73],       # grid dimensions + known structure
    }

    surfaces = [
        ("tab", TABLEAU_FLAT, 676),
        ("mct", MASTER_CT_FLAT, 868),
        ("mpt", MASTER_PT_FLAT, 868),
    ]

    for ns_name, nums in number_sets.items():
        for surf_name, flat, surf_len in surfaces:

            # 1. Start-skip: for each pair (a, b), start at a, skip by b
            for i in range(len(nums)):
                for j in range(len(nums)):
                    if i == j:
                        continue
                    start = nums[i] % surf_len
                    skip = max(1, nums[j] % surf_len)
                    key_chars = []
                    pos = start
                    for _ in range(200):
                        key_chars.append(flat[pos % surf_len])
                        pos += skip
                    yield ''.join(key_chars), f"{surf_name}_startskip_{ns_name}_{nums[i]}s{nums[j]}"

            # 2. Row-col: use sequential pairs as (row, col) starting points
            if surf_name == "tab":
                nrows, ncols = 26, 26
            else:
                nrows, ncols = GRID_ROWS, GRID_WIDTH

            grid = TABLEAU if surf_name == "tab" else (MASTER_CT if surf_name == "mct" else MASTER_PT)

            # Every pair of sequential numbers as (row, col)
            for i in range(0, len(nums) - 1, 2):
                r_start = nums[i] % nrows
                c_start = nums[i + 1] % ncols
                # Read from that position in 4 directions
                for dr, dc, dname in [(0, 1, "E"), (1, 0, "S"), (0, -1, "W"), (-1, 0, "N")]:
                    key_chars = []
                    r, c = r_start, c_start
                    for _ in range(200):
                        key_chars.append(grid[r][c])
                        r = (r + dr) % nrows
                        c = (c + dc) % ncols
                    yield ''.join(key_chars), f"{surf_name}_rc_{ns_name}_{nums[i]},{nums[i+1]}_{dname}"

        # 3. Digits-as-key: convert the number sequence to letters (mod 26) as repeating key
        key_letters = ''.join(ALPH[n % 26] for n in nums)
        yield key_letters, f"digits_az_{ns_name}"
        key_letters_ka = ''.join(KA[n % 26] for n in nums)
        yield key_letters_ka, f"digits_ka_{ns_name}"

        # Also try the numbers themselves as skip patterns on CT
        key_chars = []
        pos = 0
        ct_len = len(CT)
        for i in range(200):
            key_chars.append(CT[pos % ct_len])
            pos += max(1, nums[i % len(nums)])
        yield ''.join(key_chars), f"ct_numskip_{ns_name}"

    # Additional: K2 coordinate-derived single numbers as periods
    special_nums = [38, 57, 6, 77, 8, 44, 73, 24, 13, 11, 97, 31, 28]
    for n in special_nums:
        if n == 0:
            continue
        # Read every Nth character of master CT
        key = MASTER_CT_FLAT[::n]
        if key:
            yield key, f"mct_everyN_{n}"
        # Same for tableau
        key = TABLEAU_FLAT[::n]
        if key:
            yield key, f"tab_everyN_{n}"


# ── Family 5: Compound Paths ──────────────────────────────────────────────────

def gen_family_5a():
    """Surface indexes surface: one surface's character selects row/col of another."""
    surfaces = [
        ('tab', TABLEAU_FLAT, 26, 26),
        ('mct', MASTER_CT_FLAT, 28, 31),
        ('mpt', MASTER_PT_FLAT, 28, 31),
    ]

    for src_name, src_flat, _, _ in surfaces:
        for tgt_name, tgt_flat, tgt_rows, tgt_cols in surfaces:
            if src_name == tgt_name:
                continue
            tgt_grid = (TABLEAU if tgt_name == 'tab'
                        else MASTER_CT if tgt_name == 'mct'
                        else MASTER_PT)
            for idx_func_name, idx_func in [('az', lambda c: ALPH_IDX[c]),
                                             ('ka', lambda c: KA_IDX[c])]:
                for mode in ['row_from_src', 'col_from_src']:
                    key = []
                    for i in range(97):
                        src_char = src_flat[i % len(src_flat)]
                        idx = idx_func(src_char)
                        if mode == 'row_from_src':
                            r = idx % tgt_rows
                            c = i % tgt_cols
                        else:
                            r = i % tgt_rows
                            c = idx % tgt_cols
                        key.append(tgt_grid[r][c])
                    yield (''.join(key),
                           f'5a_{src_name}_idx_{tgt_name}_{idx_func_name}_{mode}')

            # Reverse: target character indexes into source
            src_grid = (TABLEAU if src_name == 'tab'
                        else MASTER_CT if src_name == 'mct'
                        else MASTER_PT)
            for idx_func_name, idx_func in [('az', lambda c: ALPH_IDX[c]),
                                             ('ka', lambda c: KA_IDX[c])]:
                key = ''.join(
                    src_flat[idx_func(tgt_flat[i % len(tgt_flat)]) % len(src_flat)]
                    for i in range(97)
                )
                yield (key, f'5a_{tgt_name}_revIdx_{src_name}_{idx_func_name}')


def gen_family_5b():
    """Dual-path Polybius: two paths provide row,col into tableau."""
    # Two tableau columns as row/col sources
    for c1 in range(26):
        for c2 in range(c1 + 1, 26):
            col1 = [TABLEAU[r][c1] for r in range(26)]
            col2 = [TABLEAU[r][c2] for r in range(26)]
            key = []
            for i in range(97):
                r = KA_IDX[col1[i % 26]]
                c = KA_IDX[col2[i % 26]]
                key.append(TABLEAU[r % 26][c % 26])
            yield (''.join(key), f'5b_tab_cols_{c1}_{c2}')

    # Two tableau rows as row/col sources
    for r1 in range(26):
        for r2 in range(r1 + 1, 26):
            row1 = [TABLEAU[r1][c] for c in range(26)]
            row2 = [TABLEAU[r2][c] for c in range(26)]
            key = []
            for i in range(97):
                r = KA_IDX[row1[i % 26]]
                c = KA_IDX[row2[i % 26]]
                key.append(TABLEAU[r % 26][c % 26])
            yield (''.join(key), f'5b_tab_rows_{r1}_{r2}')

    # Cross-surface: master grid column provides rows, tableau column provides cols
    for mc in range(31):
        master_col = [MASTER_CT[r][mc] for r in range(28)]
        for tc in range(26):
            tab_col = [TABLEAU[r][tc] for r in range(26)]
            key = []
            for i in range(97):
                r = KA_IDX[master_col[i % 28]] % 26
                c = KA_IDX[tab_col[i % 26]] % 26
                key.append(TABLEAU[r][c])
            yield (''.join(key), f'5b_cross_mc{mc}_tc{tc}')


def gen_family_5c():
    """Read surface, transform through tableau with keyword."""
    keywords = ['KRYPTOS', 'SEVEN', 'PALIMPSEST', 'ABSCISSA', 'DEFECTOR',
                'KOMPASS', 'HOROLOGE', 'BERLIN', 'CARTER']

    # Base sequences: sample from Families 1-2 (row reads, col reads, diags at various starts)
    base_sequences = []
    # Tableau row-major reads from all 26 start rows
    for start_row in range(26):
        seq = ''
        for r in range(26):
            row = (start_row + r) % 26
            seq += ''.join(TABLEAU[row])
        base_sequences.append((seq, f'tab_rows_start{start_row}'))

    # Tableau column-major reads
    for start_col in range(26):
        seq = ''
        for c in range(26):
            col = (start_col + c) % 26
            seq += ''.join(TABLEAU[r][col] for r in range(26))
        base_sequences.append((seq, f'tab_cols_start{start_col}'))

    # Master grid row-major and column-major
    base_sequences.append((MASTER_CT_FLAT, 'mct_flat'))
    base_sequences.append((MASTER_PT_FLAT, 'mpt_flat'))
    base_sequences.append((''.join(MASTER_CT[r][c] for c in range(31) for r in range(28)),
                           'mct_colmajor'))
    base_sequences.append((''.join(MASTER_PT[r][c] for c in range(31) for r in range(28)),
                           'mpt_colmajor'))

    for base_seq, base_name in base_sequences:
        for kw in keywords:
            # Vig: TABLEAU[KA_IDX[kw_ch]][KA_IDX[inter_ch]]
            key = []
            for i in range(min(len(base_seq), 200)):
                inter_ch = base_seq[i]
                kw_ch = kw[i % len(kw)]
                if inter_ch in KA_IDX and kw_ch in KA_IDX:
                    key.append(TABLEAU[KA_IDX[kw_ch]][KA_IDX[inter_ch]])
                else:
                    key.append('A')
            if len(key) >= 26:
                yield (''.join(key), f'5c_{base_name}_{kw}_vig')

            # Beau: TABLEAU[KA_IDX[kw_ch]][(26 - KA_IDX[inter_ch]) % 26]
            key = []
            for i in range(min(len(base_seq), 200)):
                inter_ch = base_seq[i]
                kw_ch = kw[i % len(kw)]
                if inter_ch in KA_IDX and kw_ch in KA_IDX:
                    key.append(TABLEAU[KA_IDX[kw_ch]][(26 - KA_IDX[inter_ch]) % 26])
                else:
                    key.append('A')
            if len(key) >= 26:
                yield (''.join(key), f'5c_{base_name}_{kw}_beau')


def gen_family_5d():
    """Position-mapped: key[i] = surface[f(i)]."""
    surfaces = [
        ('tab', TABLEAU_FLAT),
        ('mct', MASTER_CT_FLAT),
        ('mpt', MASTER_PT_FLAT),
    ]

    for surf_name, surf in surfaces:
        slen = len(surf)

        # Linear: f(i) = (a*i + b) % slen
        for a in range(1, 50):
            for b in range(0, slen, max(1, slen // 20)):
                key = ''.join(surf[(a * i + b) % slen] for i in range(97))
                yield (key, f'5d_{surf_name}_lin_a{a}_b{b}')

        # Quadratic: f(i) = (a*i^2 + b*i) % slen (sampled)
        for a in range(1, 20):
            for b in range(0, 20):
                key = ''.join(surf[(a * i * i + b * i) % slen] for i in range(97))
                yield (key, f'5d_{surf_name}_quad_a{a}_b{b}')

        # Fibonacci positions
        fibs = [0, 1]
        while fibs[-1] < slen * 2:
            fibs.append(fibs[-1] + fibs[-2])
        for offset in range(min(50, slen)):
            key = ''.join(surf[(fibs[i % len(fibs)] + offset) % slen] for i in range(97))
            yield (key, f'5d_{surf_name}_fib_off{offset}')

        # Coordinate-sequence mapped
        coord_seqs = [
            ('k2', [38, 57, 6, 77, 8, 44]),
            ('tomb', [25, 44, 25, 32, 36, 5]),
            ('sums', [63, 101, 32, 109, 44, 49]),
            ('dsums', [7, 8, 17, 5, 9, 11]),
        ]
        for seq_name, seq in coord_seqs:
            # Cumulative sum as position
            positions = []
            pos = 0
            for i in range(97):
                positions.append(pos % slen)
                pos += seq[i % len(seq)]
            key = ''.join(surf[p] for p in positions)
            yield (key, f'5d_{surf_name}_cumsum_{seq_name}')

            # Direct index
            key = ''.join(surf[seq[i % len(seq)] % slen] for i in range(97))
            yield (key, f'5d_{surf_name}_direct_{seq_name}')


def gen_family_5():
    """Yield all compound paths (5a-5d)."""
    yield from gen_family_5a()
    yield from gen_family_5b()
    yield from gen_family_5c()
    yield from gen_family_5d()


# ── Family 6: Morse and Physical Features ────────────────────────────────────

def gen_family_6():
    """Morse and physical features: skip patterns from keyword indices."""
    ndyahr_indices = [KA_IDX[c] for c in 'NDYAHR']
    kryptos_indices = [KA_IDX[c] for c in 'KRYPTOS']
    seven_indices = [KA_IDX[c] for c in 'SEVEN']

    surfaces = [('tab', TABLEAU_FLAT), ('mct', MASTER_CT_FLAT), ('mpt', MASTER_PT_FLAT)]

    for surf_name, surf in surfaces:
        slen = len(surf)

        # NDYAHR indices as skip pattern
        for start in range(min(100, slen)):
            pos = start
            key = []
            for i in range(97):
                key.append(surf[pos % slen])
                pos += ndyahr_indices[i % 6] + 1
            yield (''.join(key), f'6_ndyahr_skip_{surf_name}_start{start}')

        # KRYPTOS indices as skip pattern
        for start in range(min(100, slen)):
            pos = start
            key = []
            for i in range(97):
                key.append(surf[pos % slen])
                pos += kryptos_indices[i % 7] + 1
            yield (''.join(key), f'6_kryptos_skip_{surf_name}_start{start}')

        # SEVEN indices as skip pattern
        for start in range(min(100, slen)):
            pos = start
            key = []
            for i in range(97):
                key.append(surf[pos % slen])
                pos += seven_indices[i % 5] + 1
            yield (''.join(key), f'6_seven_skip_{surf_name}_start{start}')


# ══════════════════════════════════════════════════════════════════════════════
# MULTIPROCESSING WORKER
# ══════════════════════════════════════════════════════════════════════════════

def _score_batch(batch):
    """Score a batch of (key_chars, description, family_num) tuples.

    Returns list of hit dicts for scores >= THRESHOLD.
    """
    hits = []
    for key_chars, desc, fam_num in batch:
        if not key_chars or not key_chars.isalpha():
            continue
        klen = len(key_chars)
        if klen >= 97:
            for offset in range(klen - 96):
                window = key_chars[offset:offset + 97]
                results = score_key(window)
                for score, variant in results:
                    hits.append({
                        'score': score, 'variant': variant,
                        'family': fam_num, 'desc': desc,
                        'offset': offset, 'key_preview': window[:30],
                    })
        else:
            results = score_key(key_chars)
            for score, variant in results:
                hits.append({
                    'score': score, 'variant': variant,
                    'family': fam_num, 'desc': desc,
                    'offset': 0, 'key_preview': key_chars[:30],
                })
    return hits


def _decrypt_full(key_chars, variant):
    """Decrypt CT with key_chars under the given variant. Returns 97-char PT."""
    key_upper = key_chars.upper()
    key_len = len(key_upper)
    pt = []
    for i in range(len(CT)):
        k_c = key_upper[i % key_len]
        ct_c = CT[i]
        if variant == 'beau_az':
            val = (ALPH_IDX[k_c] - ALPH_IDX[ct_c]) % 26
            pt.append(ALPH[val])
        elif variant == 'vig_az':
            val = (ALPH_IDX[ct_c] - ALPH_IDX[k_c]) % 26
            pt.append(ALPH[val])
        elif variant == 'beau_ka':
            val = (KA_IDX[k_c] - KA_IDX[ct_c]) % 26
            pt.append(KA[val])
        elif variant == 'vig_ka':
            val = (KA_IDX[ct_c] - KA_IDX[k_c]) % 26
            pt.append(KA[val])
    return ''.join(pt)


# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Exhaustive Sculpture Reading Path Search v1"
    )
    parser.add_argument('--family', type=int, default=0,
                        help='Run single family (1-6) or 0=all')
    parser.add_argument('--threshold', type=int, default=12,
                        help='Minimum score to report (default: 12)')
    parser.add_argument('--workers', type=int, default=0,
                        help='Number of multiprocessing workers (0=auto, 1=serial)')
    parser.add_argument('--batch-size', type=int, default=1000,
                        help='Batch size for multiprocessing dispatch')
    args = parser.parse_args()

    global THRESHOLD
    THRESHOLD = args.threshold

    n_workers = args.workers if args.workers > 0 else cpu_count()

    families = {
        1: ("Tableau 26x26", gen_family_1),
        2: ("Master Grid 28x31", gen_family_2),
        3: ("Keyword-Parameterized", gen_family_3),
        4: ("Coordinate-Parameterized", gen_family_4),
        5: ("Compound Paths", gen_family_5),
        6: ("Morse & Physical Features", gen_family_6),
    }

    if args.family:
        if args.family not in families:
            print(f"Unknown family {args.family}. Valid: 1-6", flush=True)
            sys.exit(1)
        families = {args.family: families[args.family]}

    print("=" * 78, flush=True)
    print("SCULPTURE READING PATH SEARCH v1", flush=True)
    print(f"Threshold: {THRESHOLD}/24  Families: {sorted(families.keys())}  "
          f"Workers: {n_workers}", flush=True)
    print(f"Surfaces: TABLEAU 26x26={len(TABLEAU_FLAT)}ch, "
          f"MASTER_CT 28x31={len(MASTER_CT_FLAT)}ch, "
          f"MASTER_PT 28x31={len(MASTER_PT_FLAT)}ch", flush=True)
    print("=" * 78, flush=True)

    all_hits = []
    total_paths = 0
    total_tests = 0
    t0 = time.time()

    use_mp = n_workers > 1

    for fam_num, (fam_name, gen_func) in sorted(families.items()):
        print(f"\n--- Family {fam_num}: {fam_name} ---", flush=True)
        fam_paths = 0
        fam_tests = 0
        fam_t0 = time.time()

        if use_mp:
            # ── Multiprocessing mode ──────────────────────────────────────
            batch = []
            pool = Pool(processes=n_workers)
            pending_results = []

            for key_chars, desc in gen_func():
                if not key_chars or not key_chars.isalpha():
                    continue
                batch.append((key_chars, desc, fam_num))
                fam_paths += 1

                if len(batch) >= args.batch_size:
                    pending_results.append(pool.apply_async(_score_batch, (batch,)))
                    # Count approximate tests
                    for kc, _, _ in batch:
                        fam_tests += max(1, len(kc) - 96) if len(kc) >= 97 else 1
                    batch = []

                    if fam_paths % 10000 == 0:
                        elapsed = time.time() - fam_t0
                        print(f"  {fam_paths:>8,} paths dispatched | "
                              f"{len(pending_results)} batches | "
                              f"{elapsed:.1f}s", flush=True)

            # Flush remaining batch
            if batch:
                pending_results.append(pool.apply_async(_score_batch, (batch,)))
                for kc, _, _ in batch:
                    fam_tests += max(1, len(kc) - 96) if len(kc) >= 97 else 1

            pool.close()

            # Collect results
            print(f"  Collecting {len(pending_results)} batches...", flush=True)
            for res in pending_results:
                batch_hits = res.get()
                for h in batch_hits:
                    all_hits.append(h)
                    if h['score'] >= 18:
                        print(f'  *** SIGNAL: {h["score"]}/24 {h["variant"]} '
                              f'{h["desc"]} offset={h.get("offset", "?")}',
                              flush=True)

            pool.join()

        else:
            # ── Serial mode ───────────────────────────────────────────────
            for key_chars, desc in gen_func():
                if not key_chars or not key_chars.isalpha():
                    continue

                tests = test_path(key_chars, desc, fam_num, all_hits)
                fam_tests += tests
                fam_paths += 1

                if fam_paths % 10000 == 0:
                    elapsed = time.time() - fam_t0
                    print(f"  {fam_paths:>8,} paths | {fam_tests:>10,} tests | "
                          f"{len(all_hits)} hits >= {THRESHOLD} | "
                          f"{elapsed:.1f}s", flush=True)

        fam_elapsed = time.time() - fam_t0
        print(f"  DONE: {fam_paths:,} paths, {fam_tests:,} tests, "
              f"{len(all_hits)} total hits >= {THRESHOLD}, "
              f"{fam_elapsed:.1f}s", flush=True)

        total_paths += fam_paths
        total_tests += fam_tests

    elapsed = time.time() - t0

    # ── Summary ──────────────────────────────────────────────────────────────
    print("\n" + "=" * 78, flush=True)
    print(f"COMPLETE: {total_paths:,} paths, {total_tests:,} tests, "
          f"{elapsed:.1f}s", flush=True)
    print(f"Hits >= {THRESHOLD}/24: {len(all_hits)}", flush=True)

    all_hits.sort(key=lambda x: -x['score'])

    # ── Hit analysis ─────────────────────────────────────────────────────────
    if all_hits:
        print(f"\nTop results:", flush=True)
        for h in all_hits[:20]:
            offset_str = f" off={h.get('offset', '?')}" if 'offset' in h else ""
            print(f"  {h['score']:>2}/24 {h['variant']:<10} "
                  f"F{h['family']} {h['desc'][:55]}{offset_str}", flush=True)

        # Detailed analysis for scores >= 12
        for h in all_hits:
            if h['score'] < 12:
                break
            key_preview = h.get('key_preview', '')
            desc = h['desc']
            variant = h['variant']
            score = h['score']
            offset = h.get('offset', 0)

            # Reconstruct key for decryption
            # For long-key hits, we need the 97-char window; key_preview is only 30 chars
            # So we regenerate if possible, or just use preview info
            if score >= 18:
                print(f"\n  {'*' * 60}", flush=True)
                print(f"  *** SIGNAL *** {score}/24 {variant}", flush=True)
                print(f"  Path: {desc}", flush=True)
                print(f"  Key preview: {key_preview}", flush=True)
                print(f"  {'*' * 60}", flush=True)
            elif score >= 12:
                print(f"\n  -- Hit {score}/24 {variant} | {desc} | key: {key_preview}",
                      flush=True)
    else:
        print(f"\nNo paths scored >= {THRESHOLD}/24.", flush=True)

    # ── Save results ─────────────────────────────────────────────────────────
    output_dir = os.path.join(_ROOT, 'results')
    os.makedirs(output_dir, exist_ok=True)
    output = os.path.join(output_dir, 'f_sculpture_path_search_v1.json')

    with open(output, 'w') as f:
        json.dump({
            'total_paths': total_paths,
            'total_tests': total_tests,
            'threshold': THRESHOLD,
            'workers': n_workers,
            'elapsed_seconds': round(elapsed, 1),
            'hit_count': len(all_hits),
            'hits': all_hits[:200],
        }, f, indent=2)
    print(f"\nResults saved: {output}", flush=True)


if __name__ == '__main__':
    main()
