"""Real-data positive control for the attainable-crib-ceiling filter.

scripts/lib/test_crib_filter.py validates conventions on SYNTHETIC ciphertext.
That is necessary but not sufficient: synthetic data is generated by the same
model the filter assumes, so it cannot catch a mismatch between the model and
actual Kryptos practice.

This file runs the filter against K1 and K2 -- real, solved Kryptos panels with
published plaintext -- using a crib set shaped like the K4 hypothesis (a
contiguous 18-char prefix plus two interior runs, 42 positions, the same count
as crib level L1).

REQUIREMENT: the filter must (a) leave the TRUE configuration unEliminated and
(b) eliminate almost everything else. If it fails (a) the filter is unsound and
every elimination built on it is false. If it fails (b) it has no power.
"""
from __future__ import annotations

import os
import sys

_ROOT = os.path.dirname(os.path.abspath(__file__))
while not os.path.exists(os.path.join(_ROOT, "src")):
    _ROOT = os.path.dirname(_ROOT)
sys.path.insert(0, os.path.join(_ROOT, "src"))
sys.path.insert(0, os.path.join(_ROOT, "scripts", "lib"))
sys.path.insert(0, _ROOT)
sys.path.insert(0, os.path.join(_ROOT, "kryptosbot"))

from crib_filter import AZ, ceiling, index_table, keyword_mixed  # noqa: E402
import compute as C  # noqa: E402

K2_CT = (
    "VFPJUDEEHZWETZYVGWHKKQETGFQJNCEGGWHKKDQMCPFQZDQMMIAGPFXHQRLGTIMVMZJANQLVKQEDAGDVFRPJUNGEUNA"
    "QZGZLECGYUXUEENJTBJLBQCRTBJDFHRRYIZETKZEMVDUFKSJHKFWHKUWQLSZFTIHHDDDUVH"
    "DWKBFUFPWNTDFIYCUQZEREEVLDKFEZMOQQJLTTUGSYQPFEUNLAVIDXFLGGTEZ"
    "FKZBSFDQVGOGIPUFXHHDRKFFHQNTGPUAECNUVPDJMQCLQUMUNEDFQELZZVRRGKFFVOEEXBD"
    "MVPNFQXEZLGREDNQFMPNZGLFLPMRJQYALMGNUVPDXVKPDQUMEBEDMHDAFMJGZNUPLGEWJLLAETG"
)
PANELS = [("K1", C.K1_CT, C.K1_PT, "PALIMPSEST", 10), ("K2", K2_CT, C.K2_PT, "ABSCISSA", 8)]


def _sweep(ct, pt, kw):
    n = min(len(ct), len(pt))
    ct, pt = ct[:n], pt[:n]
    cribs = {q: pt[q] for q in
             list(range(0, 18)) + list(range(21, 34)) + list(range(min(63, n - 11), min(74, n)))}
    rows = []
    alphas = [("KRYPTOS", keyword_mixed("KRYPTOS")), ("AZ", AZ), (kw, keyword_mixed(kw))]
    for cn, ca in alphas:
        for pn, pa in alphas:
            for v in ("vig", "beau", "vbeau"):
                for p in range(1, 15):
                    c, _ = ceiling(ct, cribs, lambda q: q, lambda q, p=p: q % p,
                                   ct_tab=index_table(ca), pt_tab=index_table(pa), variant=v)
                    rows.append((c, p, v, cn, pn))
    return cribs, rows


def test_true_configuration_is_never_eliminated():
    for name, ct, pt, kw, period in PANELS:
        cribs, rows = _sweep(ct, pt, kw)
        surv = [r for r in rows if r[0] == len(cribs)]
        assert surv, f"{name}: filter eliminated EVERYTHING including the truth"
        assert any(r[1] == period for r in surv), (
            f"{name}: the TRUE period {period} was eliminated -- filter is unsound"
        )


def test_filter_has_power_on_real_panels():
    for name, ct, pt, kw, period in PANELS:
        cribs, rows = _sweep(ct, pt, kw)
        surv = [r for r in rows if r[0] == len(cribs)]
        rate = len(surv) / len(rows)
        assert rate < 0.02, f"{name}: survival rate {rate:.3%} too high, filter has no power"
        # every survivor should BE the true period (vig/vbeau are sign-equivalent)
        assert {r[1] for r in surv} == {period}, (
            f"{name}: survivors at wrong periods {sorted({r[1] for r in surv})}"
        )


def test_kryptos_alphabet_is_recovered():
    for name, ct, pt, kw, period in PANELS:
        cribs, rows = _sweep(ct, pt, kw)
        surv = [r for r in rows if r[0] == len(cribs)]
        assert all(r[3] == "KRYPTOS" for r in surv), f"{name}: wrong ct alphabet recovered"


if __name__ == "__main__":
    for name, ct, pt, kw, period in PANELS:
        cribs, rows = _sweep(ct, pt, kw)
        surv = [r for r in rows if r[0] == len(cribs)]
        print(f"{name}: {len(cribs)} cribs, {len(surv)}/{len(rows)} not eliminated "
              f"({len(surv)/len(rows):.3%}); true period {period} recovered: "
              f"{any(r[1]==period for r in surv)}")
