"""z26_linear.py -- exact affine algebra over Z_26, plus a sound injectivity decider.

Why this module exists
----------------------
Quagmire III / IV crib equations are LINEAR over Z_26 once the mixed alphabet is
treated as 26 unknowns instead of as a keyword to enumerate:

    Quagmire III   pi(c_i)   - pi(p_i)   - k[r_i] = 0        26 + P unknowns
    Quagmire IV    pi_c(c_i) - pi_p(p_i) - k[r_i] = 0        52 + P unknowns

Solving these exactly closes ALL 26! alphabets at once for a period, which no
keyword enumeration can do.  Z_26 is not a field, so nothing here uses field
Gaussian elimination directly: every system is solved mod 2 and mod 13 and the
two solution spaces are recombined by CRT (Z_26 ~= Z_2 x Z_13 as rings).

Two things are load-bearing and are handled explicitly rather than assumed:

THE CRIB SYSTEM IS HOMOGENEOUS.  Every Q3/Q4 crib equation has right-hand side
zero, so pi = const, k = 0 always solves it and `solve_z26` can NEVER return
None for these families.  "Linearly consistent" therefore carries exactly zero
information here, and any sweep that reports it as a result is reporting
nothing.  All discriminating power lives in the injectivity test below; the
natural contradiction signature is the solution space collapsing onto the
trivial orbit, where pi is constant and hence not a permutation.

GAUGE FREEDOM.  Adding a constant to every pi value leaves every Q3 equation
unchanged, and the system being homogeneous also makes every scalar multiple of
a solution a solution.  So the "no information" orbit already has 26 * 26 = 676
points, and it can be LARGER: pi(c) - pi(p) = k[r] only pins pi up to functions
affine on each coset of the subgroup generated by the key values, so a key whose
shifts share a factor with 26 inflates the trivial orbit (gcd 2 gives 13x; the
Beaufort forms have a parity analogue).  Never read dimension alone as evidence.
The injectivity decider works on pairwise DIFFERENCES, which quotients the gauge
out exactly (see `injective_point_report`).

INJECTIVITY IS THE REAL FILTER.  Q3 has 26 unknowns against 24 released-crib
equations and Q4 has 52, so linear consistency will almost never contradict
anything.  The decision that carries information is whether the affine solution
space contains a point at which pi is injective.  `injective_point_exists`
returns True / False / None, where None means INCONCLUSIVE and must never be
reported as an elimination.

API
---
    gauss_mod_p(rows, rhs, n, p)      -> (particular, nullspace_basis) | None
    solve_z26(rows, rhs, n)           -> Z26Space | None
    Z26Space                          affine space over Z_26 (.size, .dim2, .dim13,
                                      .particular, .generators, .point, .contains)
    injective_point_exists(space, letter_slots, n_letters=26) -> True|False|None
    injective_point_report(...)       -> InjectivityReport (decision + proof reason + witness)
    free_columns(rows, n)             -> columns constrained by no equation

All arithmetic is exact integer arithmetic; there is no floating point anywhere
in this module.
"""
from __future__ import annotations

import itertools
import random
from dataclasses import dataclass, field
from typing import Sequence

__all__ = [
    "gauss_mod_p",
    "solve_z26",
    "Z26Space",
    "InjectivityReport",
    "injective_point_exists",
    "injective_point_report",
    "free_columns",
    "crt",
]

Vector = tuple[int, ...]

MOD = 26
# CRT reconstruction over Z_26:  x = 13*x2 + 14*x13  (mod 26)
#   mod 2 : 13*x2 + 14*x13 = x2      mod 13 : 13*x2 + 14*x13 = x13
_C2, _C13 = 13, 14


def crt(x2: int, x13: int) -> int:
    """The unique element of Z_26 congruent to x2 mod 2 and x13 mod 13."""
    return (_C2 * x2 + _C13 * x13) % MOD


# --------------------------------------------------------------------------- 1. GF(p)

def gauss_mod_p(
    rows: Sequence[Sequence[int]],
    rhs: Sequence[int],
    n: int,
    p: int,
) -> tuple[list[int], list[list[int]]] | None:
    """Solve  rows @ x = rhs  over GF(p) exactly.

    Returns (particular, nullspace_basis), or None if the system is
    INCONSISTENT (a proof that no solution exists over GF(p)).

    * `p` must be prime; the sweeps use p in {2, 13}.
    * Rank deficiency is handled: the nullspace basis has n - rank vectors, one
      per free column, and `particular` has 0 in every free column.
    * An empty system (no rows) is consistent with the whole space.
    * Complexity O(m * n * min(m, n)); exact integer arithmetic.
    """
    if p < 2:
        raise ValueError(f"p must be a prime >= 2, got {p}")
    m = len(rows)
    if len(rhs) != m:
        raise ValueError("rows and rhs have different lengths")
    aug: list[list[int]] = []
    for row, b in zip(rows, rhs):
        if len(row) != n:
            raise ValueError(f"row of length {len(row)} in a system with n={n}")
        aug.append([x % p for x in row] + [b % p])

    pivots: list[int] = []
    r = 0
    for c in range(n):
        piv = next((i for i in range(r, m) if aug[i][c]), None)
        if piv is None:
            continue
        aug[r], aug[piv] = aug[piv], aug[r]
        inv = pow(aug[r][c], p - 2, p)          # Fermat; p prime
        aug[r] = [(x * inv) % p for x in aug[r]]
        for i in range(m):
            if i != r and aug[i][c]:
                f = aug[i][c]
                aug[i] = [(x - f * y) % p for x, y in zip(aug[i], aug[r])]
        pivots.append(c)
        r += 1
        if r == m:
            break

    # Rows below the last pivot are all-zero in the coefficient block; a
    # nonzero rhs there is a contradiction 0 = b.
    for i in range(r, m):
        assert all(aug[i][c] == 0 for c in range(n)), "internal: non-reduced tail row"
        if aug[i][n]:
            return None

    particular = [0] * n
    for i, c in enumerate(pivots):
        particular[c] = aug[i][n]
    pivotset = set(pivots)
    basis: list[list[int]] = []
    for f in range(n):
        if f in pivotset:
            continue
        v = [0] * n
        v[f] = 1
        for i, c in enumerate(pivots):
            v[c] = (-aug[i][f]) % p
        basis.append(v)
    return particular, basis


def _in_span(basis: Sequence[Sequence[int]], target: Sequence[int], n: int, p: int) -> bool:
    """Is `target` in the GF(p)-span of `basis`?"""
    if not basis:
        return all(x % p == 0 for x in target)
    k = len(basis)
    rows = [[basis[j][i] % p for j in range(k)] for i in range(n)]
    return gauss_mod_p(rows, [t % p for t in target], k, p) is not None


# --------------------------------------------------------------------------- 2. Z_26

@dataclass(frozen=True)
class Z26Space:
    """The affine solution space of a linear system over Z_26, stored CRT-split.

    A point is  x = 13*(part2 + basis2 @ c2) + 14*(part13 + basis13 @ c13)  mod 26
    with c2 in Z_2^dim2 and c13 in Z_13^dim13, and that parametrisation is a
    BIJECTION onto the solution set.  So |space| = 2**dim2 * 13**dim13 exactly.
    """

    n: int
    part2: Vector
    basis2: tuple[Vector, ...]
    part13: Vector
    basis13: tuple[Vector, ...]

    @property
    def dim2(self) -> int:
        return len(self.basis2)

    @property
    def dim13(self) -> int:
        return len(self.basis13)

    @property
    def size(self) -> int:
        """Exact number of points in the space (26**n when unconstrained)."""
        return (2 ** self.dim2) * (13 ** self.dim13)

    @property
    def particular(self) -> Vector:
        return tuple(crt(a, b) for a, b in zip(self.part2, self.part13))

    @property
    def generators(self) -> tuple[Vector, ...]:
        """Z_26 generators of the direction module (order 2 ones first, then order 13)."""
        g = [tuple((_C2 * x) % MOD for x in v) for v in self.basis2]
        g += [tuple((_C13 * x) % MOD for x in v) for v in self.basis13]
        return tuple(g)

    def point(self, c2: Sequence[int] = (), c13: Sequence[int] = ()) -> Vector:
        """Materialise the point at reduced coordinates (c2, c13); defaults to the particular."""
        c2 = list(c2) + [0] * (self.dim2 - len(c2))
        c13 = list(c13) + [0] * (self.dim13 - len(c13))
        if len(c2) != self.dim2 or len(c13) != self.dim13:
            raise ValueError("coordinate vector longer than the space dimension")
        out = []
        for i in range(self.n):
            a = self.part2[i] + sum(self.basis2[j][i] * c2[j] for j in range(self.dim2))
            b = self.part13[i] + sum(self.basis13[j][i] * c13[j] for j in range(self.dim13))
            out.append(crt(a % 2, b % 13))
        return tuple(out)

    def contains(self, x: Sequence[int]) -> bool:
        """Exact membership test for a Z_26 vector."""
        if len(x) != self.n:
            return False
        d2 = [(x[i] - self.part2[i]) % 2 for i in range(self.n)]
        d13 = [(x[i] - self.part13[i]) % 13 for i in range(self.n)]
        return (_in_span(self.basis2, d2, self.n, 2)
                and _in_span(self.basis13, d13, self.n, 13))

    def random_point(self, rng: random.Random | None = None) -> Vector:
        rng = rng or random.Random()
        return self.point([rng.randrange(2) for _ in range(self.dim2)],
                          [rng.randrange(13) for _ in range(self.dim13)])

    def describe(self) -> str:
        return (f"dim2={self.dim2} dim13={self.dim13} "
                f"|space|=2^{self.dim2}*13^{self.dim13}={self.size}")


def solve_z26(
    rows: Sequence[Sequence[int]],
    rhs: Sequence[int],
    n: int,
) -> Z26Space | None:
    """Solve  rows @ x = rhs  exactly over Z_26.  Returns None if CONTRADICTED.

    Sound because Z_26 ~= Z_2 x Z_13 as a ring (CRT): x solves the system over
    Z_26 iff x mod 2 solves it over GF(2) AND x mod 13 solves it over GF(13),
    and every (x2, x13) pair lifts to exactly one x.  So `None` here is a proof
    of NO SOLUTION for any assignment of the unknowns, and the returned space is
    the complete solution set -- not a sample of it.

    Always inspect `.size` / `.describe()`: for the Quagmire systems the space
    is never a point (gauge freedom alone guarantees that), so "not None" means
    NOT ELIMINATED, never "solved".
    """
    s2 = gauss_mod_p(rows, rhs, n, 2)
    if s2 is None:
        return None
    s13 = gauss_mod_p(rows, rhs, n, 13)
    if s13 is None:
        return None
    return Z26Space(
        n=n,
        part2=tuple(s2[0]),
        basis2=tuple(tuple(v) for v in s2[1]),
        part13=tuple(s13[0]),
        basis13=tuple(tuple(v) for v in s13[1]),
    )


def free_columns(rows: Sequence[Sequence[int]], n: int) -> list[int]:
    """Columns (unknowns) that appear in no equation with a nonzero coefficient.

    Those unknowns range over all of Z_26 independently of everything else,
    which is the precondition for the extension lemma used by the injectivity
    reduction (unconstrained letters can always absorb the leftover values).
    """
    used = [False] * n
    for row in rows:
        for c, v in enumerate(row):
            if v % MOD:
                used[c] = True
    return [c for c in range(n) if not used[c]]


# --------------------------------------------------------------------------- 3. injectivity

@dataclass(frozen=True)
class InjectivityReport:
    """Result of the injectivity decision.

    decision : True  = a witness point EXISTS; it is attached in `witness` and
                       was re-verified before being returned.
               False = PROVEN that no point of the space makes the listed slots
                       pairwise distinct.
               None  = INCONCLUSIVE (search budget exhausted).  Never an
                       elimination, never "consistent".
    """
    decision: bool | None
    reason: str
    witness: Vector | None = None
    diff_rank2: int = 0
    diff_rank13: int = 0
    n_pairs: int = 0
    exhaustive: bool = False
    nodes: int = 0
    notes: tuple[str, ...] = field(default_factory=tuple)


class _Aff:
    """An affine subspace {part + sum a_k basis_k} of GF(p)^d, closed under
    intersection with a single affine constraint.  Used to carry the surviving
    parameter space while slot values are assigned one at a time."""

    __slots__ = ("p", "part", "basis")

    def __init__(self, p: int, part: list[int], basis: list[list[int]]):
        self.p, self.part, self.basis = p, part, basis

    @classmethod
    def full(cls, p: int, d: int) -> "_Aff":
        return cls(p, [0] * d, [[1 if i == j else 0 for i in range(d)] for j in range(d)])

    @property
    def dim(self) -> int:
        return len(self.basis)

    def functional(self, coeffs: Sequence[int]) -> tuple[list[int], int]:
        """Rewrite coeffs . c  as  g . a + const  in the current coordinates."""
        p = self.p
        const = sum(x * y for x, y in zip(coeffs, self.part)) % p
        g = [sum(x * y for x, y in zip(coeffs, b)) % p for b in self.basis]
        return g, const

    def reachable(self, coeffs: Sequence[int]) -> int | None:
        """None if coeffs . c takes every value in GF(p) on this space,
        otherwise the single constant value it is pinned to."""
        g, const = self.functional(coeffs)
        return const if not any(g) else None

    def constrain(self, coeffs: Sequence[int], target: int) -> "_Aff | None":
        """Intersect with {c : coeffs . c = target}; None if that is empty."""
        p = self.p
        g, const = self.functional(coeffs)
        target %= p
        if not any(g):
            return self if const == target else None
        k0 = next(i for i, v in enumerate(g) if v)
        inv = pow(g[k0], p - 2, p)
        step = ((target - const) * inv) % p
        base = self.basis[k0]
        part = [(a + step * b) % p for a, b in zip(self.part, base)]
        basis = []
        for k, bk in enumerate(self.basis):
            if k == k0:
                continue
            f = (g[k] * inv) % p
            basis.append([(a - f * b) % p for a, b in zip(bk, base)])
        return _Aff(p, part, basis)

    def any_point(self) -> list[int]:
        return list(self.part)


def _normalise_groups(letter_slots) -> list[list[int]]:
    seq = list(letter_slots)
    if not seq:
        return []
    if all(isinstance(s, int) for s in seq):
        return [seq]
    groups = [list(g) for g in seq]
    for g in groups:
        if any(not isinstance(s, int) for s in g):
            raise TypeError("letter_slots must be a sequence of ints or a sequence of such")
    return groups


def _independent_columns(mat: list[list[int]], ncols: int, p: int) -> list[int]:
    """Indices of a maximal linearly independent set of columns of `mat` over GF(p)."""
    nrows = len(mat)
    work: list[tuple[list[int], int]] = []
    chosen: list[int] = []
    for c in range(ncols):
        v = [mat[i][c] % p for i in range(nrows)]
        for prow, pcol in work:
            if v[pcol]:
                f = v[pcol]
                v = [(a - f * b) % p for a, b in zip(v, prow)]
        piv = next((i for i in range(nrows) if v[i]), None)
        if piv is None:
            continue
        inv = pow(v[piv], p - 2, p)
        v = [(x * inv) % p for x in v]
        newwork = []
        for prow, pcol in work:
            if prow[piv]:
                f = prow[piv]
                prow = [(a - f * b) % p for a, b in zip(prow, v)]
            newwork.append((prow, pcol))
        newwork.append((v, piv))
        work = newwork
        chosen.append(c)
    return chosen


def injective_point_report(
    space: Z26Space,
    letter_slots,
    n_letters: int = MOD,
    *,
    restarts: int = 40,
    node_budget: int = 200_000,
    seed: int = 0,
) -> InjectivityReport:
    """Decide whether `space` contains a point at which the listed slots are
    pairwise distinct mod 26 -- i.e. whether the mixed alphabet can be a real
    permutation.  This, not linear consistency, is the filter that eliminates.

    `letter_slots` is either a flat sequence of variable indices (one alphabet,
    Quagmire III) or a sequence of such sequences (Quagmire IV: pi_p and pi_c
    each independently injective; equal values ACROSS groups are allowed).

    Only the CONSTRAINED slots need be listed.  If a letter appears in no
    equation its coordinate is a free column (`free_columns`), so once the
    constrained slots are pairwise distinct the unconstrained letters can always
    absorb the leftover values -- that is the reduction from "pi is a
    permutation" to "these slots are pairwise distinct".  The caller owns that
    precondition; this function decides distinctness on exactly the slots given.

    WHAT IS PROVEN VERSUS WHAT IS ONLY SEARCHED
    -------------------------------------------
    decision=True   ALWAYS SOUND.  A concrete point of the space is constructed
                    and re-verified pairwise before returning.
    decision=False  ALWAYS SOUND.  Returned only from
                      (a) pigeonhole: a group lists more slots than n_letters;
                      (b) a pair whose difference is identically zero on the
                          whole space (those two letters coincide everywhere);
                      (c) a COMPLETED depth-first search over slot values: at
                          each slot the candidate set is exactly the set of
                          values that slot can take in the surviving affine
                          space, so the tree contains a leaf for every injective
                          point of the space; exhausting it proves there is none.
    decision=None   INCONCLUSIVE: the DFS hit `node_budget` with the tree still
                    open.  Report as INCONCLUSIVE.  Never an elimination.

    Method.  Distinctness depends only on DIFFERENCES x[s]-x[t], so the gauge
    direction (add a constant to every pi value) contributes nothing and is
    quotiented out exactly -- `diff_rank2` / `diff_rank13` are the dimensions
    that actually matter, already gauge-free, and are the rigorous form of the
    connected-component reduction (a component that moves all listed slots
    together drops out here).  The search itself assigns slot values one at a
    time.  By CRT a slot's value is determined by its residue mod 2 and mod 13,
    each of which is either free on the surviving parameter space or pinned to a
    constant; that gives the exact candidate set for the slot in O(dim) work,
    and committing a value intersects the parameter space with one hyperplane
    per modulus.  Forward checking prunes a branch as soon as some later slot
    has no candidate left.
    """
    groups = _normalise_groups(letter_slots)
    for g in groups:
        if len(set(g)) != len(g):
            raise ValueError("a slot index is repeated inside one group")
        if len(g) > n_letters:
            return InjectivityReport(False, f"pigeonhole: {len(g)} slots > {n_letters} symbols",
                                     exhaustive=True)
        for s in g:
            if not 0 <= s < space.n:
                raise IndexError(f"slot {s} outside the {space.n} unknowns")

    pairs = [(a, b) for g in groups for a, b in itertools.combinations(g, 2)]
    if not pairs:
        return InjectivityReport(True, "no pair constrained", witness=space.particular,
                                 exhaustive=True)

    d2, d13 = space.dim2, space.dim13

    # ---- gauge-quotiented difference dimensions (reporting + degenerate check)
    A2 = [[(space.basis2[j][s] - space.basis2[j][t]) % 2 for j in range(d2)] for s, t in pairs]
    A13 = [[(space.basis13[j][s] - space.basis13[j][t]) % 13 for j in range(d13)] for s, t in pairs]
    r2 = len(_independent_columns(A2, d2, 2))
    r13 = len(_independent_columns(A13, d13, 13))
    for i, (s, t) in enumerate(pairs):
        if (not any(A2[i]) and (space.part2[s] - space.part2[t]) % 2 == 0
                and not any(A13[i]) and (space.part13[s] - space.part13[t]) % 13 == 0):
            return InjectivityReport(
                False, f"slots {s} and {t} are equal at every point of the space",
                diff_rank2=r2, diff_rank13=r13, n_pairs=len(pairs), exhaustive=True)

    slots = [s for g in groups for s in g]
    group_of = {s: gi for gi, g in enumerate(groups) for s in g}
    rng = random.Random(seed)

    def candidates(a2: _Aff, a13: _Aff, s: int, used: dict[int, set[int]]) -> list[int]:
        """Exactly the values slot s can take on the surviving space, minus the
        values already used inside its own group."""
        co2 = [space.basis2[j][s] % 2 for j in range(d2)]
        co13 = [space.basis13[j][s] % 13 for j in range(d13)]
        f2 = a2.reachable(co2)
        f13 = a13.reachable(co13)
        vals2 = [(space.part2[s] + f2) % 2] if f2 is not None else [0, 1]
        vals13 = [(space.part13[s] + f13) % 13] if f13 is not None else list(range(13))
        taken = used[group_of[s]]
        return [v for v in (crt(x, y) for x in vals2 for y in vals13) if v not in taken]

    def commit(a2: _Aff, a13: _Aff, s: int, v: int):
        co2 = [space.basis2[j][s] % 2 for j in range(d2)]
        co13 = [space.basis13[j][s] % 13 for j in range(d13)]
        n2 = a2.constrain(co2, (v - space.part2[s]) % 2)
        if n2 is None:
            return None
        n13 = a13.constrain(co13, (v - space.part13[s]) % 13)
        if n13 is None:
            return None
        return n2, n13

    nodes = 0
    budget_hit = False

    def finish(a2: _Aff, a13: _Aff) -> Vector:
        x = space.point(a2.any_point(), a13.any_point())
        for g in groups:                                  # defensive re-verification
            vals = [x[s] for s in g]
            assert len(set(vals)) == len(vals), "internal: bogus witness"
        return x

    def search(a2: _Aff, a13: _Aff, remaining: list[int], used: dict[int, set[int]],
               shuffle: bool) -> Vector | None:
        nonlocal nodes, budget_hit
        if not remaining:
            return finish(a2, a13)
        nodes += 1
        if nodes > node_budget:
            budget_hit = True
            return None
        cands = {s: candidates(a2, a13, s, used) for s in remaining}
        if any(not c for c in cands.values()):            # forward checking
            return None
        s = min(remaining, key=lambda q: len(cands[q]))
        rest = [q for q in remaining if q != s]
        vals = cands[s]
        if shuffle:
            vals = vals[:]
            rng.shuffle(vals)
        for v in vals:
            nxt = commit(a2, a13, s, v)
            if nxt is None:
                continue
            used[group_of[s]].add(v)
            out = search(nxt[0], nxt[1], rest, used, shuffle)
            used[group_of[s]].discard(v)
            if out is not None:
                return out
            if budget_hit:
                return None
        return None

    base2, base13 = _Aff.full(2, d2), _Aff.full(13, d13)

    # `search` is a COMPLETE depth-first search; the value order is the only
    # thing randomisation changes.  So the first pass decides the question
    # outright unless it runs out of budget, and the extra restarts exist only
    # to give the witness hunt more chances after a budget-out.
    total = 0
    for attempt in range(max(1, restarts)):
        nodes, budget_hit = 0, False
        w = search(base2, base13, list(slots),
                   {gi: set() for gi in range(len(groups))}, attempt > 0)
        total += nodes
        if w is not None:
            return InjectivityReport(True, "witness found and verified", witness=w,
                                     diff_rank2=r2, diff_rank13=r13,
                                     n_pairs=len(pairs), nodes=total)
        if not budget_hit:
            return InjectivityReport(False, "complete search: no point of the space is injective",
                                     diff_rank2=r2, diff_rank13=r13, n_pairs=len(pairs),
                                     exhaustive=True, nodes=total)
    return InjectivityReport(None, f"depth-first search hit the {node_budget}-node budget "
                                   f"on all {max(1, restarts)} attempts",
                             diff_rank2=r2, diff_rank13=r13, n_pairs=len(pairs),
                             nodes=total, notes=("INCONCLUSIVE, not an elimination",))


def injective_point_exists(space: Z26Space, letter_slots, n_letters: int = MOD, **kw) -> bool | None:
    """True / False / None.  See `injective_point_report` for the proof contract:
    True and False are both sound; None is INCONCLUSIVE and never an elimination."""
    return injective_point_report(space, letter_slots, n_letters, **kw).decision
