#!/usr/bin/env python3
"""
Phase B5: Full Generative Specification Test

Implements the complete stego mechanism from keywords + rules ONLY.
Does NOT read CONSENSUS_NULL_POSITIONS during mask generation.
Compares predicted mask to known consensus after generation.

This is the "independent reconstruction" test: can the spec alone
reproduce the consensus null positions?

Output: results/stego_mechanism/full_spec_test.json
"""
import sys, os, json
from datetime import datetime, timezone

_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(_ROOT, "src"))

from kryptos.kernel.constants import CT, CT_LEN, ALPH, ALPH_IDX, MOD
# NOTE: We deliberately do NOT import CONSENSUS_NULL_POSITIONS here.
# We will load it ONLY for validation at the end.

# ══════════════════════════════════════════════════════════════════════
# SPECIFICATION — derived from B1-B4 results
# Fill these in after running B1-B4. Placeholders use CHART:vigenere_az.
# ══════════════════════════════════════════════════════════════════════

# Keyword 1: KRYPTOS (row keyword, 7 letters)
KW_ROW = "KRYPTOS"

# Keyword 2: SEVEN (column keyword / palette generator, 5 letters)
KW_COL_PALETTE = "SEVEN"

# Keyword 3: CHART (table generator, 5 letters) — or updated from B1/B2
KW_COL_TABLE = "CHART"

# Cipher operation for table generation
TABLE_CIPHER = "vigenere_az"  # or updated from B1/B2

# Null output set — MUST be updated from B3 results
# Default: CHART:vigenere_az partition
NULL_OUTPUT_SET = frozenset([3, 8, 12, 15, 16, 19, 20, 24])

# Palette: generated by KRYPTOS × SEVEN on KA grid (prior validated finding)
KA = "KRYPTOSABCDEFGHIJLMNQUVWXZ"
PALETTE = frozenset()  # Will be computed below


def generate_palette():
    """Generate palette from KRYPTOS × SEVEN on 5-wide KA grid."""
    grid = []
    for i in range(0, len(KA), 5):
        grid.append(KA[i:i+5])
    # Row 5 may have only 1 letter

    kryptos_set = frozenset(KW_ROW)
    seven_set = frozenset(KW_COL_PALETTE)
    palette = set()

    for r, row in enumerate(grid):
        kryptos_trigger = any(row[c] in kryptos_set for c in range(min(3, len(row))))
        seven_trigger = any(row[c] in seven_set for c in range(min(3, len(row))))

        if kryptos_trigger:
            palette.add(row[0])  # col 0
        if seven_trigger and len(row) > 3:
            palette.add(row[3])  # col 3
        if not kryptos_trigger and not seven_trigger:
            palette.add(row[0])  # default col 0

    return frozenset(palette)


def classify_position(pos, ct_char):
    """Classify a single position as null or real using the spec."""
    r = pos % len(KW_ROW)   # 7
    c = pos % len(KW_COL_TABLE)  # 5

    # Compute table cipher output
    row_letter = KW_ROW[r]
    col_letter = KW_COL_TABLE[c]

    row_val = ALPH_IDX[row_letter]
    col_val = ALPH_IDX[col_letter]

    if TABLE_CIPHER == "vigenere_az":
        output = (row_val + col_val) % MOD
    elif TABLE_CIPHER == "beaufort_az":
        output = (row_val - col_val) % MOD
    else:
        raise ValueError(f"Unknown cipher: {TABLE_CIPHER}")

    cell_is_null = output in NULL_OUTPUT_SET
    char_in_palette = ct_char in PALETTE

    return cell_is_null, char_in_palette


def generate_mask():
    """Generate the complete null mask from the specification."""
    # Phase 1: classify all positions
    classifications = []
    for p in range(CT_LEN):
        cell_null, in_palette = classify_position(p, CT[p])
        classifications.append({
            "pos": p,
            "ct_char": CT[p],
            "cell_is_null": cell_null,
            "in_palette": in_palette,
        })

    # Phase 2: assign null status
    # Consensus null: palette letter in null cell
    consensus_nulls = set()
    # Track mixed cells (multiple palette letters in same null cell)
    cell_palette_positions = {}  # (r,c) -> list of palette positions in null cells
    for cl in classifications:
        if cl["cell_is_null"] and cl["in_palette"]:
            cell = (cl["pos"] % len(KW_ROW), cl["pos"] % len(KW_COL_TABLE))
            cell_palette_positions.setdefault(cell, []).append(cl["pos"])

    # Apply tiebreaker: first occurrence in each cell is null
    for cell, positions in cell_palette_positions.items():
        if len(positions) == 1:
            consensus_nulls.add(positions[0])
        else:
            # Mixed cell: first position is null, rest are real
            consensus_nulls.add(min(positions))

    # Varying nulls: non-palette positions in null cells, outside crib ranges
    # (Load crib positions for this check)
    from kryptos.kernel.constants import CRIB_POSITIONS
    varying_candidates = []
    for cl in classifications:
        if cl["cell_is_null"] and not cl["in_palette"]:
            if cl["pos"] not in CRIB_POSITIONS:
                varying_candidates.append(cl["pos"])

    return consensus_nulls, varying_candidates, classifications


def run_b5():
    global PALETTE

    results = {
        "experiment": "e_full_spec_test",
        "date": datetime.now(timezone.utc).isoformat(),
        "spec_params": {
            "kw_row": KW_ROW,
            "kw_col_palette": KW_COL_PALETTE,
            "kw_col_table": KW_COL_TABLE,
            "table_cipher": TABLE_CIPHER,
            "null_output_set": sorted(NULL_OUTPUT_SET),
        },
    }

    print("=" * 80)
    print("PHASE B5: FULL GENERATIVE SPECIFICATION TEST")
    print("=" * 80)

    # Generate palette
    PALETTE = generate_palette()
    print(f"Generated palette: {sorted(PALETTE)}")
    results["generated_palette"] = sorted(PALETTE)

    # Check against known palette
    from kryptos.kernel.constants import NULL_PALETTE
    palette_match = PALETTE == frozenset(NULL_PALETTE)
    results["palette_matches_known"] = palette_match
    print(f"Palette matches known {sorted(NULL_PALETTE)}? {palette_match}")

    if not palette_match:
        print("WARNING: Generated palette doesn't match. Spec may be wrong.")

    # Generate mask
    consensus_nulls, varying_candidates, classifications = generate_mask()

    print(f"\nPredicted consensus nulls ({len(consensus_nulls)}): {sorted(consensus_nulls)}")
    print(f"Varying null candidates ({len(varying_candidates)}): {varying_candidates}")

    results["predicted_consensus_nulls"] = sorted(consensus_nulls)
    results["varying_null_candidates"] = varying_candidates
    results["predicted_consensus_count"] = len(consensus_nulls)

    # ── Validate against known consensus ────────────────────────────
    from kryptos.kernel.constants import CONSENSUS_NULL_POSITIONS
    known = frozenset(CONSENSUS_NULL_POSITIONS)

    match_count = len(consensus_nulls & known)
    false_positives = consensus_nulls - known
    false_negatives = known - consensus_nulls

    results["validation"] = {
        "known_consensus_count": len(known),
        "predicted_count": len(consensus_nulls),
        "match_count": match_count,
        "false_positives": sorted(false_positives),
        "false_negatives": sorted(false_negatives),
        "accuracy": match_count / len(known) if known else 0,
    }

    print(f"\n── Validation ──")
    print(f"  Known consensus nulls: {len(known)}")
    print(f"  Predicted: {len(consensus_nulls)}")
    print(f"  Matches: {match_count}/{len(known)}")
    if false_positives:
        print(f"  False positives: {sorted(false_positives)}")
    if false_negatives:
        print(f"  False negatives: {sorted(false_negatives)}")

    if match_count == len(known) and len(consensus_nulls) == len(known):
        results["verdict"] = "PERFECT_RECONSTRUCTION"
        print(f"\nVERDICT: PERFECT — spec reconstructs all {len(known)} consensus nulls")
    elif match_count == len(known):
        results["verdict"] = "SUPERSET"
        print(f"\nVERDICT: SUPERSET — all known nulls found, plus {len(false_positives)} extras")
    else:
        results["verdict"] = f"PARTIAL_{match_count}_OF_{len(known)}"
        print(f"\nVERDICT: PARTIAL — {match_count}/{len(known)} consensus nulls reconstructed")

    out_path = os.path.join(_ROOT, "results", "stego_mechanism", "full_spec_test.json")
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults written to {out_path}")

    return results


if __name__ == "__main__":
    run_b5()
