"""Sketch: K4 keystream from a 1990-era public source text (M3 SKIP variant).

Category A. DSL-translatable via the `key_tape` kind.

Reference: Cicada 3301 Liber Primus uses a fixed source text whose letter
ordinals form the additive keystream, with selective characters not
consuming tape positions. The structural analogue for K4 is:

  Model:   M3 (finite tape, SKIP null rule)
  Cipher:  Beaufort A=0 (matches K1/K2/K3 pedagogical arc)
  Tape:    integer ordinals of a candidate 1990-era text, sliced at offset
  Skip:    keystream advances only at positions not declared null

The 24 crib-position keystream values (Beaufort A=0) are
JLJODEGKUKKKLOCGGBGOKTRU. For a candidate (text, offset, null_mask) to
survive, the tape values at the *unskipped* crib positions must reproduce
those 24 values.

The 60K Gutenberg sweep (eliminated) was M0/M1: no nulls, tape consumes
every position. M3 produces a genuinely different keystream from the same
text + offset, so this is not a re-test of an eliminated universe.
"""

from __future__ import annotations

# DECISION POINT 1 — source text shortlist. (RESOLVED 2026-05-11)
#
# Selected per user decision: KUBARK + Carter + NSA Cryptanalytics.
# All three are AAA-attested or AAA-context (intelligence tradecraft and
# the Egyptology reference Sanborn cited). All pre-1990 and outside the
# standard Gutenberg sweep that already eliminated generic running-key.
#
# Texts are pre-processed to alpha-only ASCII and stored under
# scratch/source_texts/. Loaded at spec-build time rather than inlined
# to keep the spec file small.
#
#   carter_vol1_alpha.txt              — Carter "The Tomb of Tut-Ankh-Amen"
#                                        (Volume I), 287K alpha chars.
#                                        Source: reference/carter_vol1.txt.
#   nsa_cryptanalytics_pt3_alpha.txt   — NSA Military Cryptanalytics
#                                        Part III, Lambros D. Callimahos,
#                                        October 1977. 270K alpha chars
#                                        from pages 10-200 (skips admin
#                                        front matter). Source:
#                                        reference/NSAmilitaryCryptalyticsPt3_1977.pdf.
#   kubark_alpha.txt                   — CIA KUBARK Counterintelligence
#                                        Interrogation (1963 declassified).
#                                        Source: reference/CIA Kubark 1-60.pdf
#                                        via tesseract OCR (image-only PDF).
#                                        Generated by scratch/ocr_kubark.sh
#                                        (file may not exist yet).

import os
from pathlib import Path

_SOURCE_TEXT_DIR = Path(__file__).resolve().parent / "source_texts"


def _load_alpha(filename: str) -> str:
    p = _SOURCE_TEXT_DIR / filename
    if not p.exists():
        raise FileNotFoundError(
            f"Pre-processed source text missing: {p}. "
            "Run extraction step before building the spec."
        )
    return p.read_text().strip()


def _candidate_texts() -> list[tuple[str, str]]:
    out = []
    out.append(("CARTER_VOL1", _load_alpha("carter_vol1_alpha.txt")))
    out.append(("NSA_CRYPTANALYTICS_PT3", _load_alpha("nsa_cryptanalytics_pt3_alpha.txt")))
    # KUBARK is OCR-pending; include only if file exists at build time.
    kubark = _SOURCE_TEXT_DIR / "kubark_alpha.txt"
    if kubark.exists():
        out.append(("KUBARK_OCR", kubark.read_text().strip()))
    return out


CANDIDATE_TEXTS: list[tuple[str, str]] = _candidate_texts()

# DECISION POINT 2 — null mask.
#
# M3 requires a null_positions list per tape. Three options:
#
#   (a) No null mask. Forces tape length = 97. Effectively M0/M1; this
#       overlaps the eliminated Gutenberg universe. Run only as a
#       sanity check that the DSL dispatch path reproduces the prior
#       null result.
#
#   (b) Single hypothesized null mask. The retired
#       CONSENSUS_NULL_POSITIONS (17 positions) is the obvious candidate
#       but is banner-labelled retired; cite it as a test case, not as a
#       fact. Tape length becomes 80.
#
#   (c) Number-theoretic skip predicate (Cicada parallel). e.g. skip
#       positions where pos in primes < 97, or pos % 7 in {0, 1, 2}.
#       Enumerate the predicate as a ParamRange. Tape length per
#       predicate.
#
# Pick one option for the first dispatch. Defaulting to (a) below for the
# minimal sketch; switch when shortlist is filled.

NULL_OPTION = "primes"  # "none" | "consensus_retired" | "mod7_residue_012" | "primes"


def _text_to_ord_tape(text: str, offset: int, length: int) -> list[int]:
    """Strip non-letters, uppercase, return ord(c)-ord('A') tape of given length."""
    clean = "".join(c for c in text.upper() if "A" <= c <= "Z")
    sliced = clean[offset : offset + length]
    if len(sliced) < length:
        raise ValueError(
            f"text too short at offset {offset}: have {len(sliced)} need {length}"
        )
    return [ord(c) - ord("A") for c in sliced]


def build_spec() -> "HypothesisSpec":  # type: ignore[name-defined]
    from kryptosbot.hypothesis_dsl import (
        HypothesisSpec,
        CipherLayer,
        ParamRange,
        NullBaselineSpec,
    )

    if not CANDIDATE_TEXTS:
        raise RuntimeError(
            "Fill CANDIDATE_TEXTS (decision point 1) before constructing the spec."
        )

    # Tape length depends on null mask. For NULL_OPTION='none', tape = 97.
    if NULL_OPTION == "none":
        tape_length = 97
        null_positions: tuple[int, ...] = ()
        null_rule = None
        null_tag = "no_null_mask"
    elif NULL_OPTION == "consensus_retired":
        # Banner: retired claim; test purpose only.
        from kryptos.kernel.retired import CONSENSUS_NULL_POSITIONS  # type: ignore
        null_positions = tuple(sorted(CONSENSUS_NULL_POSITIONS))
        tape_length = 97 - len(null_positions)
        null_rule = "skip"
        null_tag = "model_dependent_nulls"
    elif NULL_OPTION == "mod7_residue_012":
        null_positions = tuple(i for i in range(97) if i % 7 in (0, 1, 2))
        tape_length = 97 - len(null_positions)
        null_rule = "skip"
        null_tag = "model_dependent_nulls"
    elif NULL_OPTION == "primes":
        # Prime-indexed null skip. Cicada / Liber Primus parallel: solved
        # Liber Primus pages use prime-indexed character skips. 24 primes
        # under 97 -> tape length 73. Six of 24 crib positions are
        # nullified (23, 29, 31 in EAST group; 67, 71, 73 in BERLIN group),
        # leaving 18 crib constraints observable.
        def _is_prime(n: int) -> bool:
            if n < 2:
                return False
            for d in range(2, int(n ** 0.5) + 1):
                if n % d == 0:
                    return False
            return True
        null_positions = tuple(i for i in range(97) if _is_prime(i))
        tape_length = 97 - len(null_positions)
        null_rule = "skip"
        null_tag = "model_dependent_nulls"
    else:
        raise ValueError(f"unknown NULL_OPTION={NULL_OPTION!r}")

    # Offset sweep — coarse, hand-runnable breadth.
    offsets = list(range(0, 500, 25))  # 20 offsets per text

    # Enumerate (text, offset) -> integer tape.
    tape_values: list[list[int]] = []
    for label, body in CANDIDATE_TEXTS:
        for off in offsets:
            try:
                tape_values.append(_text_to_ord_tape(body, off, tape_length))
            except ValueError:
                # Text too short at this offset; skip.
                continue

    params = [
        ParamRange(name="tape", values=tape_values),
        ParamRange(name="variant", values=["beaufort"]),  # K1-K3 family default
        ParamRange(name="alphabet", values=["AZ"]),
    ]
    if null_positions:
        params.append(ParamRange(name="null_positions", values=[null_positions]))
        params.append(ParamRange(name="null_rule", values=[null_rule]))

    layer = CipherLayer(kind="key_tape", alphabet="AZ", params=params)

    spec = HypothesisSpec(
        hypothesis_id="cicada_parallel_public_source_keystream_v1",
        pipeline=[layer],
        crib_alignment="direct_positional",
        scoring="crib_plus_bean",
        null_baseline=NullBaselineSpec(
            method="matched_variant_family",  # match the M3-SKIP family, not random text
            n_samples=5000,
        ),
        # Budget chosen BEFORE seeing any result. ~N_texts * 20 offsets each,
        # each config evaluates 24 crib positions + Bean + ngram. ~5 minutes
        # for the minimal shortlist.
        compute_budget_cpu_minutes=10,
        assumption_bundle=[
            "az_a0",
            "ct97_direct_positional",
            null_tag,
            "beaufort_only",  # not testing vigenere/var_beaufort in this spec
            "cicada_liber_primus_parallel",  # provenance tag, optional but helpful
        ],
        # Kill criteria fixed BEFORE run. Primes null mask preserves
        # 18 of 24 crib positions; max observable crib_score is 18.
        # Thresholds calibrated from a 200K-trial MC under random
        # additive keystream over 18 positions:
        #   - per-trial mean    ≈ 0.69 (matches 18/26)
        #   - per-trial 99th    = 3
        #   - max-over-40 99th  = 5
        #   - p(score >= 13)    ≈ 1.16e-13 family-wise
        kill_criteria={
            "max_crib_score_below": 8,   # comfortably above noise ceiling
            "require_bean_passed_count_ge": 1,
            "require_ngram_floor_pass_count_ge": 1,
            "null_baseline_z_min": 2.0,
        },
        success_criteria={
            "crib_score_ge": 13,         # ~SIGNAL band scaled to 18-ceiling
            "bean_passed": True,
            "ngram_score_le": -4.0,
        },
        notes=(
            "Cicada 3301 Liber Primus parallel: candidate 1990-era public "
            "source text supplies the additive keystream; SKIP null rule "
            "differentiates this universe from the eliminated Gutenberg "
            "running-key sweep (which was M0/M1, no nulls)."
        ),
    )
    return spec


if __name__ == "__main__":
    spec = build_spec()
    print("spec_hash:           ", spec.spec_hash)
    print("expected_cardinality:", spec.expected_cardinality())
    print("compute_budget_min:  ", spec.compute_budget_cpu_minutes)
    print("null_baseline:       ", spec.null_baseline)
    print("assumption_bundle:   ", spec.assumption_bundle)
    print("kill_criteria:       ", spec.kill_criteria)
    print("success_criteria:    ", spec.success_criteria)
    errors = spec.validate()
    print("validate() errors:   ", errors if errors else "NONE")
