#!/usr/bin/env python3
"""
Cipher: non-columnar transposition
Family: transposition/other
Status: active
Keyspace: see implementation
Last run: 
Best score: 
"""
"""
E-SOLVE-12: Keystream Transposition Hypothesis

HYPOTHESIS: The substitution keystream was generated by transposing a PERIODIC key
through a columnar transposition. That is:
  1. Start with a periodic key of period p (repeating keyword)
  2. Apply a columnar transposition to the 97-character keystream
  3. The transposed keystream is then used for Vigenere or Beaufort encryption

This means: the keystream at crib positions is NOT periodic, but it IS a permutation
of periodic values. The crib-derived keystream values should cluster onto fewer
distinct residues than expected for random.

APPROACH:
For each period p in {2..13}:
  For each columnar transposition width w in {3..12}:
    For each column ordering (w! permutations, pruned by constraint propagation):
      - Compute: for each crib position i, find where it came from in the
        pre-transposition keystream (invert the columnar transposition)
      - That source position maps to a periodic residue class (source % p)
      - All crib positions mapping to the same residue class must have the
        same keystream value
      - Check if all 24 crib constraints are simultaneously satisfiable
      - If consistent: reconstruct full keystream, decrypt, score

For columnar transposition:
  - Write row-by-row into grid of width w, read column-by-column in column order
  - If len=97, nrows=ceil(97/w), last row may be short
  - Inversion: given output position, find input position
"""

import sys
import time
import json
import math
from itertools import permutations
from collections import defaultdict

sys.path.insert(0, "src")

from kryptos.kernel.constants import (
    CT, CT_LEN, ALPH, ALPH_IDX, MOD,
    CRIB_DICT, CRIB_POSITIONS, N_CRIBS,
    BEAN_EQ, BEAN_INEQ,
    VIGENERE_KEY_ENE, VIGENERE_KEY_BC,
    BEAUFORT_KEY_ENE, BEAUFORT_KEY_BC,
    NOISE_FLOOR, SIGNAL_THRESHOLD,
)
from kryptos.kernel.scoring.aggregate import score_candidate
from kryptos.kernel.constraints.bean import verify_bean, verify_bean_simple

CT_VALS = [ALPH_IDX[c] for c in CT]

# Build crib keystream maps for both variants
VIG_KEY = {}
for i, v in enumerate(VIGENERE_KEY_ENE):
    VIG_KEY[21 + i] = v
for i, v in enumerate(VIGENERE_KEY_BC):
    VIG_KEY[63 + i] = v

BEAU_KEY = {}
for i, v in enumerate(BEAUFORT_KEY_ENE):
    BEAU_KEY[21 + i] = v
for i, v in enumerate(BEAUFORT_KEY_BC):
    BEAU_KEY[63 + i] = v

CRIB_POSITIONS_SORTED = sorted(CRIB_DICT.keys())


def columnar_transposition_map(width, length, col_order):
    """
    Compute the output-to-input mapping for columnar transposition.

    Write input row-by-row into grid of given width.
    Read columns in col_order.

    Returns: output_to_input[out_pos] = in_pos
    That is, output[out_pos] = input[in_pos].
    """
    nrows = math.ceil(length / width)
    full_cols = length - (nrows - 1) * width  # number of columns with nrows elements
    # If length is exactly divisible, all columns are full
    if length % width == 0:
        full_cols = width

    # Number of elements in each column (by original column index)
    col_lengths = []
    for c in range(width):
        if c < full_cols:
            col_lengths.append(nrows)
        else:
            col_lengths.append(nrows - 1)

    # Build output-to-input mapping
    # Read columns in col_order
    output_to_input = [0] * length
    out_idx = 0
    for col_rank in range(width):
        col = col_order[col_rank]  # which original column to read
        for row in range(col_lengths[col]):
            in_pos = row * width + col
            if in_pos < length:
                output_to_input[out_idx] = in_pos
                out_idx += 1

    return output_to_input


def invert_map(mapping):
    """Invert a permutation mapping: input_to_output from output_to_input."""
    inv = [0] * len(mapping)
    for out_pos, in_pos in enumerate(mapping):
        inv[in_pos] = out_pos
    return inv


def check_consistency(source_positions, crib_keystream, period):
    """
    Check if the keystream values at crib positions are consistent with
    a periodic key of given period, after the source positions have been
    determined by inverting the columnar transposition.

    source_positions: dict {crib_pos: source_pos_in_pretransposition_keystream}
    crib_keystream: dict {crib_pos: keystream_value}
    period: period of the underlying key

    Returns: (consistent, residue_assignments)
    where residue_assignments maps residue_class -> key_value (or None if inconsistent)
    """
    residue_assignments = {}  # residue -> assigned key value

    for crib_pos in CRIB_POSITIONS_SORTED:
        source = source_positions[crib_pos]
        residue = source % period
        kval = crib_keystream[crib_pos]

        if residue in residue_assignments:
            if residue_assignments[residue] != kval:
                return False, None
        else:
            residue_assignments[residue] = kval

    return True, residue_assignments


def reconstruct_keystream(residue_assignments, period, width, col_order, length=CT_LEN):
    """
    Given residue assignments (residue -> key_value), period, and columnar transposition
    parameters, reconstruct the full 97-character keystream.

    Steps:
    1. Build the pre-transposition periodic keystream
    2. Apply the columnar transposition to get the actual keystream

    For residues not in residue_assignments, we try all 26 values (but for
    decryption we only need to check if the result is good).
    """
    # Build output_to_input map (output[out_pos] = input[in_pos])
    output_to_input = columnar_transposition_map(width, length, col_order)

    # Pre-transposition keystream: periodic with given period
    # Some residues may not be assigned (no crib constraint).
    # For those, we'd need to brute-force, but let's first try with
    # all unassigned residues set to 0 (just to score the crib positions).
    pre_trans = [0] * length
    assigned_residues = set(residue_assignments.keys())
    unassigned = [r for r in range(period) if r not in assigned_residues]

    for pos in range(length):
        residue = pos % period
        if residue in residue_assignments:
            pre_trans[pos] = residue_assignments[residue]
        else:
            pre_trans[pos] = 0  # placeholder

    # Apply columnar transposition: output[out_pos] = pre_trans[in_pos]
    keystream = [0] * length
    for out_pos in range(length):
        in_pos = output_to_input[out_pos]
        keystream[out_pos] = pre_trans[in_pos]

    return keystream, unassigned


def decrypt_vig(keystream):
    """Decrypt CT using Vigenere: PT[i] = (CT[i] - K[i]) mod 26"""
    return "".join(ALPH[(CT_VALS[i] - keystream[i]) % MOD] for i in range(CT_LEN))


def decrypt_beau(keystream):
    """Decrypt CT using Beaufort: PT[i] = (K[i] - CT[i]) mod 26"""
    return "".join(ALPH[(keystream[i] - CT_VALS[i]) % MOD] for i in range(CT_LEN))


def decrypt_var_beau(keystream):
    """Decrypt CT using Variant Beaufort: PT[i] = (CT[i] + K[i]) mod 26"""
    return "".join(ALPH[(CT_VALS[i] + keystream[i]) % MOD] for i in range(CT_LEN))


def brute_unassigned(keystream_template, unassigned_residues, period, width, col_order,
                     crib_keystream, variant_name, decrypt_fn):
    """
    For configurations with unassigned residues, try all 26^|unassigned| combinations.
    Only feasible for small numbers of unassigned residues (<=3).
    Returns best (score, plaintext, keystream, config_detail) or None.
    """
    n_unassigned = len(unassigned_residues)
    if n_unassigned > 3:
        # Too many to brute force; just score with placeholder
        return None

    output_to_input = columnar_transposition_map(width, CT_LEN, col_order)

    best_score = 0
    best_result = None

    # Try all combinations for unassigned residues
    for combo in range(26 ** n_unassigned):
        vals = []
        tmp = combo
        for _ in range(n_unassigned):
            vals.append(tmp % 26)
            tmp //= 26

        # Build pre-transposition keystream
        extra_assignments = dict(zip(unassigned_residues, vals))
        pre_trans = list(keystream_template)  # already has assigned residues

        for pos in range(CT_LEN):
            residue = pos % period
            if residue in extra_assignments:
                pre_trans[pos] = extra_assignments[residue]

        # Apply columnar transposition
        keystream = [0] * CT_LEN
        for out_pos in range(CT_LEN):
            keystream[out_pos] = pre_trans[output_to_input[out_pos]]

        # Decrypt and score
        pt = decrypt_fn(keystream)
        sc = sum(1 for pos, ch in CRIB_DICT.items() if pos < len(pt) and pt[pos] == ch)

        if sc > best_score:
            best_score = sc
            bean_result = verify_bean(keystream)
            best_result = (sc, pt, keystream, bean_result, extra_assignments)

    return best_result


print("=" * 78)
print("E-SOLVE-12: Keystream Transposition Hypothesis")
print("=" * 78)
print()
print(f"CT: {CT}")
print(f"CT length: {CT_LEN}")
print(f"Crib positions: {CRIB_POSITIONS_SORTED}")
print(f"N cribs: {N_CRIBS}")
print()
print("Vigenere keystream at cribs:")
print(f"  ENE (21-33): {VIGENERE_KEY_ENE}")
print(f"  BC  (63-73): {VIGENERE_KEY_BC}")
print("Beaufort keystream at cribs:")
print(f"  ENE (21-33): {BEAUFORT_KEY_ENE}")
print(f"  BC  (63-73): {BEAUFORT_KEY_BC}")
print()

# ── Main search ──────────────────────────────────────────────────────────

total_configs = 0
consistent_configs = 0
bean_pass_configs = 0
best_global_score = 0
best_global_detail = None
above_noise_results = []

t0 = time.time()

PERIODS = range(2, 14)       # 2..13
WIDTHS = range(3, 13)        # 3..12

VARIANTS = [
    ("vigenere", VIG_KEY, decrypt_vig),
    ("beaufort", BEAU_KEY, decrypt_beau),
]

# For widths >= 10, use constraint propagation instead of full enumeration
# w=10: 3.6M perms, w=11: 40M, w=12: 479M — too slow for brute force
MAX_WIDTH_BRUTE = 9  # enumerate all perms for w <= 9


def get_col_element_positions(width, length):
    """For each original column c, return the set of input positions in that column."""
    nrows = math.ceil(length / width)
    full_cols = length - (nrows - 1) * width
    if length % width == 0:
        full_cols = width

    col_positions = {}
    col_len = {}
    for c in range(width):
        n = nrows if c < full_cols else nrows - 1
        col_len[c] = n
        col_positions[c] = [row * width + c for row in range(n) if row * width + c < length]
    return col_positions, col_len


def get_output_offset_for_col(col_rank, col_order, col_lengths):
    """Compute the starting output index for the col_rank-th column read."""
    offset = 0
    for r in range(col_rank):
        offset += col_lengths[col_order[r]]
    return offset


def search_with_constraint_prop(width, period, crib_keystream, decrypt_fn, variant_name):
    """
    Search column orderings using constraint propagation for large widths.

    For each partial column ordering, check if the crib positions that would
    be placed so far are consistent. Prune early if not.
    """
    nrows = math.ceil(CT_LEN / width)
    full_cols = CT_LEN - (nrows - 1) * width
    if CT_LEN % width == 0:
        full_cols = width

    col_positions, col_len = get_col_element_positions(width, CT_LEN)

    # For each column c, find which crib positions' OUTPUT indices fall into the
    # range that column c would occupy IF placed at a given rank.
    # Actually, simpler: for a partial ordering, compute the output positions
    # assigned so far and check consistency.

    results = {
        "tested": 0,
        "consistent": 0,
        "best_score": 0,
        "best_detail": None,
        "above_noise": [],
        "bean_pass": 0,
    }

    crib_pos_set = set(CRIB_POSITIONS_SORTED)

    def backtrack(partial_order, used_cols, output_offset, residue_map):
        """
        partial_order: columns placed so far (list of col indices)
        used_cols: set of columns already placed
        output_offset: next output position
        residue_map: dict {residue -> key_value} from constraints seen so far
        """
        rank = len(partial_order)

        if rank == width:
            # Complete ordering — this passed all checks during construction
            results["tested"] += 1
            results["consistent"] += 1

            col_order = tuple(partial_order)
            output_to_input = columnar_transposition_map(width, CT_LEN, col_order)

            source_positions = {}
            for crib_pos in CRIB_POSITIONS_SORTED:
                source_positions[crib_pos] = output_to_input[crib_pos]

            # We already verified consistency during backtracking, but reconstruct anyway
            keystream, unassigned = reconstruct_keystream(
                residue_map, period, width, col_order, CT_LEN
            )

            if len(unassigned) == 0:
                pt = decrypt_fn(keystream)
                sc = sum(1 for pos, ch in CRIB_DICT.items()
                         if pos < len(pt) and pt[pos] == ch)
                bean_result = verify_bean(keystream)
                if bean_result.passed:
                    results["bean_pass"] += 1
                if sc > results["best_score"] or (sc == results["best_score"] and bean_result.passed):
                    results["best_score"] = sc
                    results["best_detail"] = {
                        "variant": variant_name,
                        "period": period,
                        "width": width,
                        "col_order": list(col_order),
                        "score": sc,
                        "bean_pass": bean_result.passed,
                        "plaintext": pt,
                        "residue_assignments": dict(residue_map),
                        "n_unassigned": 0,
                    }
                if sc > NOISE_FLOOR:
                    results["above_noise"].append({
                        "variant": variant_name,
                        "period": period,
                        "width": width,
                        "col_order": list(col_order),
                        "score": sc,
                        "bean_pass": bean_result.passed,
                        "plaintext": pt[:40] + "...",
                    })
            elif len(unassigned) <= 3:
                pre_trans_template = [0] * CT_LEN
                for pos in range(CT_LEN):
                    residue = pos % period
                    if residue in residue_map:
                        pre_trans_template[pos] = residue_map[residue]
                result = brute_unassigned(
                    pre_trans_template, unassigned, period, width, col_order,
                    crib_keystream, variant_name, decrypt_fn
                )
                if result is not None:
                    sc, pt, ks, bean_result, extra = result
                    if bean_result.passed:
                        results["bean_pass"] += 1
                    if sc > results["best_score"] or (sc == results["best_score"] and bean_result.passed):
                        results["best_score"] = sc
                        full_res = dict(residue_map)
                        full_res.update(extra)
                        results["best_detail"] = {
                            "variant": variant_name,
                            "period": period,
                            "width": width,
                            "col_order": list(col_order),
                            "score": sc,
                            "bean_pass": bean_result.passed,
                            "plaintext": pt,
                            "residue_assignments": full_res,
                            "n_unassigned": len(unassigned),
                        }
                    if sc > NOISE_FLOOR:
                        results["above_noise"].append({
                            "variant": variant_name,
                            "period": period,
                            "width": width,
                            "col_order": list(col_order),
                            "score": sc,
                            "bean_pass": bean_result.passed,
                            "plaintext": pt[:40] + "...",
                            "n_unassigned": len(unassigned),
                        })
            return

        # Try placing each unused column at the current rank
        for col in range(width):
            if col in used_cols:
                continue

            # Check constraints: what crib positions fall in the output range
            # for this column at this rank?
            col_length = col_len[col]
            new_output_start = output_offset
            new_output_end = output_offset + col_length

            # Check if any crib positions fall in [new_output_start, new_output_end)
            new_residue_map = dict(residue_map)
            ok = True

            for out_pos in range(new_output_start, new_output_end):
                if out_pos in crib_pos_set:
                    # This output position is a crib position
                    # The input position is: the (out_pos - new_output_start)-th
                    # element of column `col`
                    row_in_col = out_pos - new_output_start
                    in_pos = row_in_col * width + col
                    residue = in_pos % period
                    kval = crib_keystream[out_pos]

                    if residue in new_residue_map:
                        if new_residue_map[residue] != kval:
                            ok = False
                            break
                    else:
                        new_residue_map[residue] = kval

            if ok:
                partial_order.append(col)
                used_cols.add(col)
                backtrack(partial_order, used_cols, output_offset + col_length, new_residue_map)
                partial_order.pop()
                used_cols.discard(col)

    backtrack([], set(), 0, {})
    return results


def process_result(sc, pt, bean_result, variant_name, period, width, col_order,
                   residue_assignments, n_unassigned):
    """Process a single result and update global tracking."""
    global best_global_score, best_global_detail, bean_pass_configs

    if bean_result.passed:
        bean_pass_configs += 1

    if sc > best_global_score or (sc == best_global_score and bean_result.passed):
        best_global_score = sc
        best_global_detail = {
            "variant": variant_name,
            "period": period,
            "width": width,
            "col_order": list(col_order),
            "score": sc,
            "bean_pass": bean_result.passed,
            "plaintext": pt,
            "residue_assignments": residue_assignments,
            "n_unassigned": n_unassigned,
        }

    if sc > NOISE_FLOOR:
        above_noise_results.append({
            "variant": variant_name,
            "period": period,
            "width": width,
            "col_order": list(col_order),
            "score": sc,
            "bean_pass": bean_result.passed,
            "plaintext": pt[:40] + "...",
        })


for variant_name, crib_keystream, decrypt_fn in VARIANTS:
    print(f"\n{'─' * 78}")
    print(f"Variant: {variant_name}")
    print(f"{'─' * 78}")

    variant_consistent = 0
    variant_tested = 0
    variant_best_score = 0
    variant_best_detail = None

    for period in PERIODS:
        for width in WIDTHS:
            nrows = math.ceil(CT_LEN / width)
            full_cols = CT_LEN - (nrows - 1) * width
            if CT_LEN % width == 0:
                full_cols = width

            if width > MAX_WIDTH_BRUTE:
                # Use constraint propagation for large widths
                cp_results = search_with_constraint_prop(
                    width, period, crib_keystream, decrypt_fn, variant_name
                )
                tested_this_wp = cp_results["tested"]
                consistent_this_wp = cp_results["consistent"]
                best_score_this_wp = cp_results["best_score"]

                total_configs += tested_this_wp
                variant_tested += tested_this_wp
                consistent_configs += consistent_this_wp
                variant_consistent += consistent_this_wp
                bean_pass_configs += cp_results["bean_pass"]
                above_noise_results.extend(cp_results["above_noise"])

                if cp_results["best_detail"] is not None:
                    d = cp_results["best_detail"]
                    if d["score"] > best_global_score or (d["score"] == best_global_score and d.get("bean_pass", False)):
                        best_global_score = d["score"]
                        best_global_detail = d
                    if d["score"] > variant_best_score:
                        variant_best_score = d["score"]
                        variant_best_detail = d

                elapsed = time.time() - t0
                n_explored = tested_this_wp  # constraint prop explored this many complete orderings
                print(f"  p={period:2d} w={width:2d}: [CP] {n_explored:>10,} complete, "
                      f"{consistent_this_wp:>6,} consistent, "
                      f"best={best_score_this_wp}/24, "
                      f"elapsed={elapsed:.1f}s")
                continue

            # Brute force for small widths
            tested_this_wp = 0
            consistent_this_wp = 0
            best_score_this_wp = 0

            for col_order in permutations(range(width)):
                total_configs += 1
                variant_tested += 1
                tested_this_wp += 1

                # Compute output-to-input map
                output_to_input = columnar_transposition_map(width, CT_LEN, col_order)

                # For each crib position, find source position
                source_positions = {}
                for crib_pos in CRIB_POSITIONS_SORTED:
                    source_positions[crib_pos] = output_to_input[crib_pos]

                # Check consistency
                consistent, residue_assignments = check_consistency(
                    source_positions, crib_keystream, period
                )

                if not consistent:
                    continue

                consistent_configs += 1
                variant_consistent += 1
                consistent_this_wp += 1

                # Reconstruct keystream and decrypt
                keystream, unassigned = reconstruct_keystream(
                    residue_assignments, period, width, col_order, CT_LEN
                )

                if len(unassigned) == 0:
                    # Full keystream determined — decrypt and score
                    pt = decrypt_fn(keystream)
                    sc = sum(1 for pos, ch in CRIB_DICT.items()
                             if pos < len(pt) and pt[pos] == ch)

                    bean_result = verify_bean(keystream)

                    if sc > best_score_this_wp:
                        best_score_this_wp = sc

                    if bean_result.passed:
                        bean_pass_configs += 1

                    if sc > best_global_score or (sc == best_global_score and bean_result.passed):
                        best_global_score = sc
                        best_global_detail = {
                            "variant": variant_name,
                            "period": period,
                            "width": width,
                            "col_order": list(col_order),
                            "score": sc,
                            "bean_pass": bean_result.passed,
                            "plaintext": pt,
                            "residue_assignments": residue_assignments,
                            "n_unassigned": 0,
                        }

                    if sc > NOISE_FLOOR:
                        above_noise_results.append({
                            "variant": variant_name,
                            "period": period,
                            "width": width,
                            "col_order": list(col_order),
                            "score": sc,
                            "bean_pass": bean_result.passed,
                            "plaintext": pt[:40] + "...",
                        })

                    if sc > variant_best_score:
                        variant_best_score = sc
                        variant_best_detail = {
                            "variant": variant_name,
                            "period": period,
                            "width": width,
                            "col_order": list(col_order),
                            "score": sc,
                            "bean_pass": bean_result.passed,
                            "plaintext": pt,
                        }

                elif len(unassigned) <= 3:
                    # Small number of unassigned residues — brute force them
                    pre_trans_template = [0] * CT_LEN
                    for pos in range(CT_LEN):
                        residue = pos % period
                        if residue in residue_assignments:
                            pre_trans_template[pos] = residue_assignments[residue]

                    result = brute_unassigned(
                        pre_trans_template, unassigned, period, width, col_order,
                        crib_keystream, variant_name, decrypt_fn
                    )
                    if result is not None:
                        sc, pt, ks, bean_result, extra = result

                        if bean_result.passed:
                            bean_pass_configs += 1

                        if sc > best_score_this_wp:
                            best_score_this_wp = sc

                        if sc > best_global_score or (sc == best_global_score and bean_result.passed):
                            best_global_score = sc
                            full_residues = dict(residue_assignments)
                            full_residues.update(extra)
                            best_global_detail = {
                                "variant": variant_name,
                                "period": period,
                                "width": width,
                                "col_order": list(col_order),
                                "score": sc,
                                "bean_pass": bean_result.passed,
                                "plaintext": pt,
                                "residue_assignments": full_residues,
                                "n_unassigned": len(unassigned),
                            }

                        if sc > NOISE_FLOOR:
                            above_noise_results.append({
                                "variant": variant_name,
                                "period": period,
                                "width": width,
                                "col_order": list(col_order),
                                "score": sc,
                                "bean_pass": bean_result.passed,
                                "plaintext": pt[:40] + "...",
                                "n_unassigned": len(unassigned),
                            })

                        if sc > variant_best_score:
                            variant_best_score = sc
                            variant_best_detail = {
                                "variant": variant_name,
                                "period": period,
                                "width": width,
                                "col_order": list(col_order),
                                "score": sc,
                                "bean_pass": bean_result.passed,
                                "plaintext": pt,
                            }

                else:
                    # Too many unassigned — just note it's consistent
                    pt = decrypt_fn(keystream)
                    sc = sum(1 for pos, ch in CRIB_DICT.items()
                             if pos < len(pt) and pt[pos] == ch)

                    if sc > best_score_this_wp:
                        best_score_this_wp = sc

                    if sc > best_global_score:
                        best_global_score = sc
                        best_global_detail = {
                            "variant": variant_name,
                            "period": period,
                            "width": width,
                            "col_order": list(col_order),
                            "score": sc,
                            "bean_pass": False,
                            "plaintext": pt,
                            "residue_assignments": residue_assignments,
                            "n_unassigned": len(unassigned),
                            "note": f"{len(unassigned)} unassigned residues (not brute-forced)"
                        }

            if tested_this_wp > 0:
                elapsed = time.time() - t0
                print(f"  p={period:2d} w={width:2d}: {tested_this_wp:>10,} perms, "
                      f"{consistent_this_wp:>6,} consistent "
                      f"({100*consistent_this_wp/tested_this_wp:.2f}%), "
                      f"best={best_score_this_wp}/24, "
                      f"elapsed={elapsed:.1f}s")

    print(f"\n  {variant_name} summary: {variant_tested:,} tested, "
          f"{variant_consistent:,} consistent, best={variant_best_score}/24")
    if variant_best_detail:
        print(f"  Best config: p={variant_best_detail['period']}, "
              f"w={variant_best_detail['width']}, "
              f"col_order={variant_best_detail['col_order']}")
        print(f"  Bean: {'PASS' if variant_best_detail['bean_pass'] else 'FAIL'}")
        print(f"  PT: {variant_best_detail['plaintext']}")

# ── Summary ──────────────────────────────────────────────────────────────

elapsed = time.time() - t0
print(f"\n{'=' * 78}")
print("FINAL SUMMARY")
print(f"{'=' * 78}")
print(f"Total configs tested: {total_configs:,}")
print(f"Consistent configs:   {consistent_configs:,} ({100*consistent_configs/max(1,total_configs):.4f}%)")
print(f"Bean-passing configs: {bean_pass_configs:,}")
print(f"Time elapsed:         {elapsed:.1f}s")
print(f"Best global score:    {best_global_score}/24")
print()

if best_global_detail:
    print("Best configuration:")
    print(f"  Variant:    {best_global_detail['variant']}")
    print(f"  Period:     {best_global_detail['period']}")
    print(f"  Width:      {best_global_detail['width']}")
    print(f"  Col order:  {best_global_detail['col_order']}")
    print(f"  Score:      {best_global_detail['score']}/24")
    print(f"  Bean:       {'PASS' if best_global_detail['bean_pass'] else 'FAIL'}")
    if 'n_unassigned' in best_global_detail:
        print(f"  Unassigned: {best_global_detail['n_unassigned']} residues")
    print(f"  Plaintext:  {best_global_detail['plaintext']}")
    if 'residue_assignments' in best_global_detail:
        print(f"  Residues:   {best_global_detail['residue_assignments']}")

    # Full scoring through canonical path
    if best_global_detail['score'] >= NOISE_FLOOR:
        print("\n  Canonical scoring:")
        sb = score_candidate(best_global_detail['plaintext'])
        print(f"  {sb.summary}")

print()
if above_noise_results:
    print(f"Above-noise results ({len(above_noise_results)}):")
    for r in above_noise_results[:20]:
        print(f"  {r['variant']} p={r['period']} w={r['width']} "
              f"col={r['col_order']} -> {r['score']}/24 "
              f"bean={'PASS' if r['bean_pass'] else 'FAIL'} "
              f"PT={r['plaintext']}")
    if len(above_noise_results) > 20:
        print(f"  ... and {len(above_noise_results) - 20} more")
else:
    print("No above-noise results found.")

print()
classification = "NOISE" if best_global_score <= NOISE_FLOOR else (
    "SIGNAL" if best_global_score >= SIGNAL_THRESHOLD else "INTERESTING"
)
print(f"VERDICT: {classification}")
print(f"Best score {best_global_score}/24 — {'above' if best_global_score > NOISE_FLOOR else 'at or below'} noise floor ({NOISE_FLOOR})")

# Save results
results = {
    "experiment": "E-SOLVE-12",
    "hypothesis": "Keystream generated by columnar transposition of periodic key",
    "total_configs": total_configs,
    "consistent_configs": consistent_configs,
    "bean_pass_configs": bean_pass_configs,
    "best_score": best_global_score,
    "best_config": best_global_detail,
    "above_noise_count": len(above_noise_results),
    "verdict": classification,
    "elapsed_seconds": elapsed,
    "periods_tested": list(PERIODS),
    "widths_tested": list(WIDTHS),
    "variants_tested": ["vigenere", "beaufort"],
}

output_path = "results/e_solve_12_keystream_transposition.json"
try:
    with open(output_path, "w") as f:
        json.dump(results, f, indent=2, default=str)
    print(f"\nResults saved to {output_path}")
except Exception as e:
    print(f"\nCould not save results: {e}")
